/// The interface's words, in the twelve languages the project ships.
///
/// A flat map per language rather than a code-generated bundle: this is one
/// screen with about seventy strings, and a missing key falling back to English
/// is better behaviour than a build that fails because a translation is late.
///
/// The locale list matches `internal/i18n` exactly, so a user who ran the old
/// studio finds their language here under the same name. The WORDING is new —
/// these are this interface's controls, not the previous one's.
library;

import 'package:flutter/widgets.dart';

class Lang {
  const Lang(this.code, this.endonym, this._values);

  final String code;
  final String endonym;
  final Map<String, String> _values;

  String get(String key) => _values[key] ?? _en[key] ?? key;

  /// Whether this language defines the key itself rather than borrowing the
  /// English one. Exposed for the completeness test: comparing the STRINGS
  /// cannot tell a fallback from a word that is genuinely the same in both
  /// languages, and "Export" is the same in half of them.
  bool has(String key) => _values.containsKey(key);

  /// Every key this language defines, for tests.
  Iterable<String> get keys => _values.keys;
}

const _keys = <String>[
  'runs',
  'style',
  'detail',
  'source',
  'generate',
  'export',
  'inject',
  'editShapes',
  'crop',
  'before',
  'after',
  'dropTitle',
  'dropSub',
  'chooseFile',
  'chooseAnother',
  'ready',
  'noImage',
  'building',
  'finished',
  'failed',
  'readyToInject',
  'buildShapes',
  'polishEdges',
  'finish',
  'activity',
  'all',
  'problems',
  'results',
  'copy',
  'clear',
  'close',
  'done',
  'reset',
  'applyCrop',
  'free',
  'template',
  'advanced',
  'search',
  'open',
  'delete',
  'nothingSaved',
  'noMatch',
  'undo',
  'redo',
  'saveToRuns',
  'editing',
  'nothingSelected',
  'colour',
  'opacity',
  'layers',
  'back',
  'forward',
  'mirrorH',
  'mirrorV',
  'duplicate',
  'injectTitle',
  'templateLayers',
  'templateLayersHelp',
  'scale',
  'saveReload',
  'writing',
  'estimating',
  'engineFailed',
  'allRuns',
  'help',
  'helpStep1',
  'helpStep1Body',
  'helpStep2',
  'helpStep2Body',
  'helpStep3',
  'helpStep3Body',
  'helpStep4',
  'helpStep4Body',
  'helpStep5',
  'helpStep5Body',
  'helpWarning',
  'stopRun',
  'view',
  'cancel',
  'load',
  'loadRunTitle',
  'loadRunBody',
  'deleteRunTitle',
  'deleteRunBody',
  'savePreset',
  'myPresets',
  'presetName',
  'save',
  'advancedTitle',
  'bestOf',
  'bestOfHelp',
  'diagnostics',
  'openLogFolder',
  'copyPath',
  'logHint',
  'srcRes',
  'srcResHelp',
  'keepIn',
  'keepInHelp',
  'fastMode',
  'fastModeHelp',
  'dropContour',
  'dropContourHelp',
  'dropFalseEdge',
  'dropFalseEdgeHelp',
  'singleColour',
  'singleColourHelp',
  'economy',
  'economyHelp',
  'shapesWord',
  'stopSticker',
  'stopBumper',
  'stopMax',
  'customCount',
  'settings',
  'soundOnFinish',
  'soundOnFinishHelp',
  'flashOnFinish',
  'flashOnFinishHelp',
  'logButton',
  'toolSelect',
  'toolEdit',
  'rendering',
  'tagline',
  'aboutEngine',
  'aboutIdle',
  'aboutInjection',
  'injReady',
  'injNotElevated',
  'injUnavailable',
  'savedRuns',
  'injectWarn',
  'openLibraryFolder',
  'fieldSize',
  'fieldAngle',
  'etaLeft',
  'dropHere',
  'toolEllipse',
  'toolRect',
  'toolTriangle',
  'newLayer',
  'moveHere',
  'groupSelect',
  'lockLayer',
  'hideLayer',
  'sortName',
  'sortDate',
  'select',
  'selectAll',
  'selectNone',
  'today',
  'yesterday',
  'earlier',
  'deleteManyTitle',
  'deleteManyBody',
  'bank',
  'overCap',
  'reference',
  'createScratch',
  'expertTitle',
  'expertWarn',
  'expertReset',
  'expertGroupSmooth',
  'expertGroupShapes',
  'expertGroupSearch',
  'kPolish',
  'kPolishHelp',
  'kPolishIters',
  'kPolishItersHelp',
  'kPolishTau',
  'kPolishTauHelp',
  'kAlpha',
  'kAlphaHelp',
  'kAlphaMin',
  'kAlphaMinHelp',
  'kWeightStrength',
  'kWeightStrengthHelp',
  'kAspect',
  'kAspectHelp',
  'kKinds',
  'kKindsHelp',
  'kKindWeights',
  'kKindWeightsHelp',
  'kBoundary',
  'kBoundaryHelp',
  'kBackfit',
  'kBackfitHelp',
  'kCompact',
  'kCompactHelp',
  'kStandout',
  'kStandoutHelp',
  'kGrid',
  'kGridHelp',
  'kQuality',
  'kQualityHelp',
  'kSeed',
  'kSeedHelp',
  'kRandom',
  'kRandomHelp',
  'kMutated',
  'kMutatedHelp',
  'kSample',
  'kSampleHelp',
  'kPatience',
  'kPatienceHelp',
  'kOverdraw',
  'kOverdrawHelp',
  'kRampWeight',
  'kRampWeightHelp',
  'stopRunTitle',
  'stopRunBody',
  'injectShort',
  'metaDropIn',
  'metaPreparing',
  'metaShapesOf',
  'metaShapesDone',
  'retry',
  'shortcuts',
  'discardEditsTitle',
  'discardEditsBody',
];

/// Builds a catalogue from a list parallel to [_keys]. Positional rather than
/// keyed so a translation cannot silently omit an entry: a short list is a
/// compile-time length mismatch caught by the test, not a string that quietly
/// falls back to English in one language only.
Map<String, String> _cat(List<String> v) {
  assert(
    v.length == _keys.length,
    'catalogue has ${v.length} of ${_keys.length}',
  );
  return {for (var i = 0; i < _keys.length; i++) _keys[i]: v[i]};
}

final _en = _cat([
  'Runs',
  'STYLE',
  'DETAIL',
  'SOURCE',
  'Generate',
  'Export',
  'Inject',
  'Edit',
  'Crop',
  'before',
  'after',
  'Drop an image here',
  'a photo, a drawing, a logo — it becomes vinyl shapes',
  'Choose file…',
  'Choose another…',
  'ready — pick a style and a detail, then generate',
  'No image',
  'Building shapes',
  'Finished',
  'Failed',
  'ready to inject',
  'Build shapes',
  'Polish edges',
  'Finish',
  'ACTIVITY',
  'All',
  'Problems',
  'Results',
  'Copy',
  'Clear',
  'Close',
  'Done',
  'Reset',
  'Apply crop',
  'Free',
  'Template',
  'Advanced settings…',
  'Search',
  'Open',
  'Delete',
  'Nothing saved yet — every finished run lands here.',
  'No run matches that.',
  'Undo',
  'Redo',
  'Save to runs',
  'Editing',
  'Nothing selected',
  'COLOUR',
  'OPACITY',
  'LAYERS',
  'Back',
  'Forward',
  'Mirror H',
  'Mirror V',
  'Duplicate',
  'INJECT INTO FH6',
  'Template layers',
  'the exact layer count of the group open in the editor',
  'Scale',
  'Save and reload the vinyl in FH6 afterwards',
  'Writing…',
  'estimating…',
  'The engine did not start',
  'All',
  'How it works',
  'Pick a picture',
  'Drop one on the window or click the source at the bottom left. Crop it if only part of it should become a decal.',
  'Choose a style and a size',
  'The style tells the engine what kind of picture this is. The size is how many shapes it may spend — 3000 fills a whole panel.',
  'Generate',
  'Watch it build. Drag across the picture to compare the result with the original. Stopping early keeps what is already there.',
  'Open the game',
  'In FH6, start a new vinyl group from a template and open it in the Vinyl Group Editor. Enter that template’s exact layer count here.',
  'Send it over',
  'Press the transfer button. Then SAVE the vinyl in the game and load it again — FH6 only rebuilds the shapes on reload.',
  'The game must be running with a template group open in the editor. Nothing is written to your saved designs — only to the group you have open.',
  'Stop',
  'View',
  'Cancel',
  'Load',
  'Load this run?',
  'What is on the canvas now will be replaced.',
  'Delete this run?',
  'This cannot be undone.',
  'Save these settings…',
  'My presets',
  'Preset name',
  'Save',
  'Advanced settings',
  'Attempts per run',
  'Runs the whole pipeline N times and keeps the best. N times slower.',
  'Diagnostics',
  'Open log folder',
  'Copy path',
  'If something goes wrong, send this file.',
  'Use source resolution',
  'Fit at the image\'s real resolution. Much slower on big sources.',
  'Keep shapes inside image',
  'Every shape stays inside the picture. Prevents edge spill.',
  'Fast mode',
  'Scores a quarter of the candidates. Far quicker, 2-6% more error.',
  'Drop the contour term',
  'Helps about half of images, hurts the rest. Compare by eye.',
  'Drop the false-edge term',
  'Turn off when the result looks too soft.',
  'Single colour',
  'One solid colour on a clean cutout. No grey antialiased edges.',
  'Economy mode',
  'Re-fits every shape as it builds. Best under 1500 shapes.',
  'shapes',
  'sticker',
  'bumper',
  'maximum',
  'or type a number',
  'Settings',
  'Sound when a run finishes',
  'A short chime when the shapes are ready.',
  'Flash the taskbar when finished',
  'Only when the window is in the background.',
  'Log',
  'Select',
  'Edit',
  'rendering…',
  'a picture becomes vinyl shapes',
  'Engine',
  'idle',
  'Injection',
  'ready',
  'available, not elevated',
  'unavailable here',
  'Saved runs',
  'Injection writes into the running game. Save and reload the vinyl afterwards — FH6 only rebuilds it then.',
  'Open library folder',
  'SIZE',
  'ANGLE',
  'about {t} left',
  'Drop it',
  'Ellipse',
  'Rectangle',
  'Triangle',
  'New layer',
  'Move shape here',
  'Select the whole layer',
  'Lock',
  'Hide',
  'Name',
  'Date',
  'Select',
  'All',
  'None',
  'Today',
  'Yesterday',
  'Earlier',
  'Delete {n} runs?',
  'They go for good, with their shapes.',
  'Bank',
  'over the game\'s 3000 limit',
  'Reference',
  'Create from scratch',
  'Expert tuning',
  'The engine’s own defaults, editable. They ship tuned; change them to trade '
      'time for quality or to chase a look. A dot marks what you changed.',
  'Reset all',
  'Smoothness & crispness',
  'Edges & shapes',
  'Search & quality',
  'Joint polish',
  'Refines all shapes together after placement. Off = raw output: faster, rougher.',
  'Polish iterations',
  'More iterations settle edges and colours further. Time grows with the number.',
  'Final edge softness',
  'Where sharpening ends. Lower = crisper edges, higher = softer blends.',
  'Semi-transparent shapes',
  'Translucent layers build smooth gradients with fewer shapes. Off = every shape opaque.',
  'Opacity floor',
  'The most transparent a shape may be. Higher = crisper, but gradients need more shapes.',
  'Detail weighting',
  'How much the fit favours detailed areas over flat ones. 0 = all pixels equal.',
  'Max stretch',
  'How elongated a shape may get. Higher traces contours with thin slivers.',
  'Shape kinds',
  'Comma list of ellipse, triangle, rectangle. Fewer kinds = a more stylized look.',
  'Kind mix',
  'Relative share of each kind, in the same order as the list above.',
  'Boundary-aware size',
  'Shrinks candidates near strong edges. Helps portraits; hurts text and flat art.',
  'Back-fit pass',
  'Re-places the least useful shapes against the finished picture. Never worse, costs time.',
  'Prefer compact shapes',
  'Penalizes sprawling shapes that stretch across unrelated regions.',
  'Standout cleanup',
  'Removes shapes whose rim draws an edge the picture lacks. 0 = off; judge the result by eye.',
  'Search grid',
  'Cells of the placement search. Finer targets small details, spreads the start more thinly.',
  'Search preset',
  'One dial for the search budgets below. Any count you edit overrides its tier.',
  'Seed',
  'Same seed, same settings, same result. Change it to reroll the composition.',
  'Candidates per shape',
  'Random placements tried for every shape. More = better fits, slower.',
  'Refinement tries',
  'Hill-climb budget spent improving each shape’s best candidate.',
  'Score samples',
  'Pixels sampled when scoring a candidate. More = exacter scores, slower.',
  'Search patience',
  'Stop after this many shapes in a row bring no improvement. High = spend the full budget.',
  'Overdraw',
  'Generate this many times more shapes, keep the best. Opaque styles only.',
  'Gradient boost',
  'Extra shape budget for smooth gradients so they render without visible facets.',
  'Stop the fit?',
  'The shapes placed so far will be discarded.',
  'Only {n} of {m} shapes fit — the rest will be dropped in-game. Use a larger template.',
  'drop something in',
  'preparing…',
  '{n} of {m} shapes',
  '{n} shapes · {b}',
  'Retry',
  'Keyboard shortcuts',
  'Discard your edits?',
  'The shapes you changed in the editor will be lost.',
]);

final _uk = _cat([
  'Прогони',
  'СТИЛЬ',
  'ДЕТАЛІЗАЦІЯ',
  'ДЖЕРЕЛО',
  'Згенерувати',
  'Експорт',
  'Перенести в гру',
  'Редагувати',
  'Обрізати',
  'до',
  'після',
  'Перетягніть зображення сюди',
  'фото, малюнок, логотип — стане вініловими фігурами',
  'Вибрати файл…',
  'Вибрати інший…',
  'готово — оберіть стиль і деталізацію, тоді генеруйте',
  'Немає зображення',
  'Будую фігури',
  'Готово',
  'Помилка',
  'можна переносити в гру',
  'Побудова фігур',
  'Шліфування країв',
  'Завершення',
  'ЖУРНАЛ',
  'Усе',
  'Проблеми',
  'Результати',
  'Копіювати',
  'Очистити',
  'Закрити',
  'Готово',
  'Скинути',
  'Застосувати',
  'Вільно',
  'Шаблон',
  'Додаткові налаштування…',
  'Пошук',
  'Відкрити',
  'Видалити',
  'Поки порожньо — кожен завершений прогін потрапляє сюди.',
  'Нічого не знайдено.',
  'Скасувати',
  'Повторити',
  'Зберегти в прогони',
  'Редагування',
  'Нічого не вибрано',
  'КОЛІР',
  'ПРОЗОРІСТЬ',
  'ШАРИ',
  'Назад',
  'Вперед',
  'Дзеркало Г',
  'Дзеркало В',
  'Дублювати',
  'ПЕРЕНЕСТИ В FH6',
  'Шарів у шаблоні',
  'точна кількість шарів групи, відкритої в редакторі',
  'Масштаб',
  'Після вставки збережіть і перезавантажте вініл у грі',
  'Записую…',
  'рахую…',
  'Двигун не запустився',
  'Усі',
  'Як користуватись',
  'Візьміть зображення',
  'Перетягніть його на вікно або клацніть джерело внизу ліворуч. Обріжте, якщо декалем має стати лише частина.',
  'Оберіть стиль і розмір',
  'Стиль каже двигунові, що це за зображення. Розмір — скільки фігур можна витратити: 3000 заповнюють цілу панель.',
  'Згенеруйте',
  'Дивіться, як будується. Проведіть по зображенню, щоб порівняти результат з оригіналом. Зупинка лишає вже зроблене.',
  'Відкрийте гру',
  'У FH6 створіть групу вінілу з шаблону і відкрийте її в редакторі груп. Введіть тут точну кількість шарів цього шаблону.',
  'Перенесіть',
  'Натисніть кнопку перенесення. Потім ЗБЕРЕЖІТЬ вініл у грі й завантажте знову — FH6 перебудовує фігури лише при перезавантаженні.',
  'Гра має бути запущена, а група з шаблону — відкрита в редакторі. У ваші збережені дизайни нічого не пишеться, лише у відкриту групу.',
  'Зупинити',
  'Перегляд',
  'Скасувати',
  'Завантажити',
  'Завантажити цей прогін?',
  'Те, що зараз на полотні, буде замінено.',
  'Видалити цей прогін?',
  'Це не можна скасувати.',
  'Зберегти ці налаштування…',
  'Мої пресети',
  'Назва пресета',
  'Зберегти',
  'Розширені налаштування',
  'Спроб на прогін',
  'Проганяє весь конвеєр N разів і лишає найкращий. У N разів довше.',
  'Діагностика',
  'Відкрити теку з логом',
  'Копіювати шлях',
  'Якщо щось піде не так, надішліть цей файл.',
  'Нативна роздільність',
  'Підганяти на справжній роздільності зображення. На великих — значно довше.',
  'Тримати фігури в межах зображення',
  'Кожна фігура лишається всередині картинки. Прибирає виліт за край.',
  'Швидкий режим',
  'Оцінює чверть кандидатів. Помітно швидше, похибка більша на 2-6%.',
  'Прибрати контурний член',
  'Приблизно половині зображень допомагає, решті шкодить. Порівнюйте оком.',
  'Прибрати член хибних країв',
  'Вимкніть, якщо результат виглядає надто мʼяким.',
  'Один колір',
  'Одна суцільна заливка на чистому вирізі. Без сірих згладжених країв.',
  'Ощадливий режим',
  'Перепідганяє кожну фігуру під час побудови. Найкраще до 1500 фігур.',
  'фігур',
  'стікер',
  'бампер',
  'максимум',
  'або введіть число',
  'Налаштування',
  'Звук після завершення',
  'Короткий сигнал, коли фігури готові.',
  'Блимати в панелі задач',
  'Тільки коли вікно у фоні.',
  'Лог',
  'Вибір',
  'Редагувати',
  'малюємо…',
  'зображення стає віниловими фігурами',
  'Двигун',
  'простій',
  'Перенесення',
  'готове',
  'доступне, без прав адміністратора',
  'тут недоступне',
  'Збережених прогонів',
  'Перенесення пише в запущену гру. Після нього збережіть і перезавантажте вініл — FH6 перебудовує його лише тоді.',
  'Відкрити теку бібліотеки',
  'РОЗМІР',
  'КУТ',
  'лишилось близько {t}',
  'Відпускайте',
  'Еліпс',
  'Прямокутник',
  'Трикутник',
  'Новий шар',
  'Перенести фігуру сюди',
  'Вибрати весь шар',
  'Замкнути',
  'Сховати',
  'Назва',
  'Дата',
  'Вибрати',
  'Усі',
  'Зняти',
  'Сьогодні',
  'Учора',
  'Раніше',
  'Видалити прогонів: {n}?',
  'Вони зникнуть назавжди, разом із фігурами.',
  'Банк',
  'понад ліміт гри 3000',
  'Оригінал',
  'Створити з нуля',
  'Експертне налаштування',
  'Власні параметри двигуна, доступні для правки. Стандартні значення вже '
      'виважені; змінюйте, щоб обміняти час на якість або знайти свій стиль. '
      'Крапка позначає змінене.',
  'Скинути все',
  'Гладкість і чіткість',
  'Краї та фігури',
  'Пошук і якість',
  'Спільне полірування',
  'Доводить усі фігури разом після розстановки. Вимкнено = сирий результат: швидше, грубіше.',
  'Ітерації полірування',
  'Більше ітерацій — рівніші краї та кольори. Час росте разом із числом.',
  'М’якість країв',
  'Де закінчується загострення. Менше = чіткіші краї, більше = м’якші переходи.',
  'Напівпрозорі фігури',
  'Прозорі шари будують плавні градієнти меншою кількістю фігур. Вимкнено = всі фігури непрозорі.',
  'Поріг непрозорості',
  'Наскільки прозорою може бути фігура. Вище = чіткіше, але градієнтам треба більше фігур.',
  'Вага деталей',
  'Наскільки припасування віддає перевагу деталям над рівними ділянками. 0 = всі пікселі рівні.',
  'Макс. видовження',
  'Наскільки витягнутою може бути фігура. Більше — тонкі смужки вздовж контурів.',
  'Види фігур',
  'Список через кому: ellipse, triangle, rectangle. Менше видів = стилізованіший вигляд.',
  'Пропорції видів',
  'Частка кожного виду, у тому ж порядку, що список вище.',
  'Розмір біля країв',
  'Зменшує кандидатів біля сильних країв. Помагає портретам; шкодить тексту й плоскій графіці.',
  'Дорозстановка',
  'Переставляє найменш корисні фігури проти готової картини. Не буває гірше, коштує часу.',
  'Компактні фігури',
  'Штрафує розлогі фігури, що тягнуться через непов’язані ділянки.',
  'Чистка чужорідних',
  'Прибирає фігури, чий обідок малює край, якого нема на картині. 0 = вимкнено; результат судіть оком.',
  'Сітка пошуку',
  'Клітинки пошуку розміщення. Дрібніша цілить у дрібні деталі, але розпорошує старт.',
  'Пресет пошуку',
  'Один перемикач для бюджетів пошуку нижче. Змінене число переважає свій рівень.',
  'Сід',
  'Той самий сід і налаштування — той самий результат. Змініть, щоб перетасувати композицію.',
  'Кандидатів на фігуру',
  'Скільки випадкових розміщень пробується для кожної фігури. Більше = точніше, повільніше.',
  'Спроби доведення',
  'Бюджет підйому, що покращує найкращого кандидата фігури.',
  'Пікселі оцінки',
  'Скільки пікселів вибирається для оцінки кандидата. Більше = точніші оцінки, повільніше.',
  'Терпіння пошуку',
  'Зупинитись після стількох фігур поспіль без покращення. Багато = витратити весь бюджет.',
  'Перебір фігур',
  'Згенерувати у стільки разів більше фігур і лишити найкращі. Лише для непрозорих стилів.',
  'Підсилення градієнтів',
  'Додатковий бюджет фігур для плавних градієнтів, щоб вони не розпадались на грані.',
  'Зупинити генерацію?',
  'Усі розміщені досі фігури будуть відкинуті.',
  'Вміщується лише {n} з {m} фігур — решту гра відкине. Візьміть більший шаблон.',
  'перетягніть зображення',
  'підготовка…',
  '{n} з {m} фігур',
  '{n} фігур · {b}',
  'Спробувати ще раз',
  'Гарячі клавіші',
  'Відхилити зміни?',
  'Зміни, зроблені в редакторі, буде втрачено.',
]);

final _de = _cat([
  'Läufe',
  'STIL',
  'DETAIL',
  'QUELLE',
  'Erzeugen',
  'Export',
  'Einfügen',
  'Bearbeiten',
  'Zuschneiden',
  'vorher',
  'nachher',
  'Bild hierher ziehen',
  'ein Foto, eine Zeichnung, ein Logo — wird zu Vinylformen',
  'Datei wählen…',
  'Andere wählen…',
  'bereit — Stil und Detail wählen, dann erzeugen',
  'Kein Bild',
  'Formen werden gebaut',
  'Fertig',
  'Fehlgeschlagen',
  'bereit zum Einfügen',
  'Formen bauen',
  'Kanten schleifen',
  'Abschluss',
  'AKTIVITÄT',
  'Alle',
  'Probleme',
  'Ergebnisse',
  'Kopieren',
  'Leeren',
  'Schließen',
  'Fertig',
  'Zurücksetzen',
  'Zuschnitt übernehmen',
  'Frei',
  'Vorlage',
  'Erweiterte Einstellungen…',
  'Suchen',
  'Öffnen',
  'Löschen',
  'Noch nichts gespeichert — jeder fertige Lauf landet hier.',
  'Kein Lauf passt dazu.',
  'Rückgängig',
  'Wiederholen',
  'In Läufe speichern',
  'Bearbeiten',
  'Nichts ausgewählt',
  'FARBE',
  'DECKKRAFT',
  'EBENEN',
  'Zurück',
  'Vor',
  'Spiegeln H',
  'Spiegeln V',
  'Duplizieren',
  'IN FH6 EINFÜGEN',
  'Ebenen der Vorlage',
  'die genaue Ebenenzahl der im Editor geöffneten Gruppe',
  'Skalierung',
  'Danach das Vinyl in FH6 speichern und neu laden',
  'Schreibe…',
  'schätze…',
  'Die Engine startete nicht',
  'Alle',
  'So funktioniert es',
  'Bild wählen',
  _en['helpStep1Body']!,
  'Stil und Größe wählen',
  _en['helpStep2Body']!,
  'Erzeugen',
  _en['helpStep3Body']!,
  'Spiel öffnen',
  _en['helpStep4Body']!,
  'Übertragen',
  _en['helpStep5Body']!,
  _en['helpWarning']!,
  'Stoppen',
  'Ansicht',
  'Abbrechen',
  'Laden',
  'Diesen Lauf laden?',
  'Was jetzt auf der Leinwand liegt, wird ersetzt.',
  'Diesen Lauf löschen?',
  'Das lässt sich nicht rückgängig machen.',
  'Diese Einstellungen speichern…',
  'Meine Presets',
  'Preset-Name',
  'Speichern',
  'Erweiterte Einstellungen',
  'Versuche pro Lauf',
  'Lässt die ganze Pipeline N-mal laufen und behält das beste Ergebnis. N-mal langsamer.',
  'Diagnose',
  'Log-Ordner öffnen',
  'Pfad kopieren',
  'Wenn etwas schiefgeht, schicken Sie diese Datei.',
  'Originalauflösung verwenden',
  'Rechnet in der echten Auflösung des Bildes. Bei großen Vorlagen deutlich langsamer.',
  'Formen im Bild halten',
  'Jede Form bleibt innerhalb des Bildes. Verhindert Überstehen am Rand.',
  'Schnellmodus',
  'Bewertet ein Viertel der Kandidaten. Deutlich schneller, 2-6% mehr Fehler.',
  'Konturterm weglassen',
  'Hilft etwa der Hälfte der Bilder und schadet dem Rest. Nach Augenmaß vergleichen.',
  'Fehlkanten-Term weglassen',
  'Ausschalten, wenn das Ergebnis zu weich wirkt.',
  'Einfarbig',
  'Eine deckende Farbe auf einem sauberen Freisteller. Keine grauen Kanten.',
  'Sparmodus',
  'Passt jede Form beim Aufbau neu an. Am besten unter 1500 Formen.',
  'Formen',
  'Sticker',
  'Stoßstange',
  'Maximum',
  'oder Zahl eingeben',
  'Einstellungen',
  'Ton, wenn ein Lauf fertig ist',
  'Ein kurzer Ton, sobald die Formen fertig sind.',
  'Taskleiste blinken lassen',
  'Nur wenn das Fenster im Hintergrund ist.',
  'Protokoll',
  'Auswahl',
  'Bearbeiten',
  'wird gezeichnet…',
  'aus einem Bild werden Vinyl-Formen',
  'Engine',
  'bereit',
  'Übertragung',
  'bereit',
  'verfügbar, ohne Adminrechte',
  'hier nicht verfügbar',
  'Gespeicherte Läufe',
  'Die Übertragung schreibt ins laufende Spiel. Danach das Vinyl speichern und neu laden — FH6 baut es erst dann neu auf.',
  'Bibliotheksordner öffnen',
  'GRÖSSE',
  'WINKEL',
  'noch etwa {t}',
  'Loslassen',
  'Ellipse',
  'Rechteck',
  'Dreieck',
  'Neue Ebene',
  'Form hierher verschieben',
  'Ganze Ebene auswählen',
  'Sperren',
  'Ausblenden',
  'Name',
  'Datum',
  'Auswählen',
  'Alle',
  'Keine',
  'Heute',
  'Gestern',
  'Früher',
  '{n} Läufe löschen?',
  'Sie sind endgültig weg, samt ihren Formen.',
  'Bank',
  'über dem Spiellimit von 3000',
  'Referenz',
  'Von Grund auf neu',
  'Experten-Tuning',
  'Die eigenen Vorgaben der Engine, editierbar. Sie sind ab Werk abgestimmt; '
      'ändern heißt Zeit gegen Qualität tauschen oder einem Look nachjagen. '
      'Ein Punkt markiert Geändertes.',
  'Alles zurücksetzen',
  'Glätte & Schärfe',
  'Kanten & Formen',
  'Suche & Qualität',
  'Gemeinsamer Feinschliff',
  'Verfeinert alle Formen zusammen nach der Platzierung. Aus = Rohergebnis: schneller, gröber.',
  'Feinschliff-Iterationen',
  'Mehr Iterationen beruhigen Kanten und Farben weiter. Die Zeit wächst mit der Zahl.',
  'Finale Kantenweichheit',
  'Wo das Schärfen endet. Niedriger = schärfere Kanten, höher = weichere Übergänge.',
  'Halbtransparente Formen',
  'Durchscheinende Ebenen bauen weiche Verläufe mit weniger Formen. Aus = alles deckend.',
  'Deckkraft-Untergrenze',
  'Wie transparent eine Form höchstens sein darf. Höher = knackiger, aber Verläufe brauchen mehr Formen.',
  'Detail-Gewichtung',
  'Wie stark der Fit detailreiche Bereiche bevorzugt. 0 = alle Pixel gleich.',
  'Max. Streckung',
  'Wie langgezogen eine Form werden darf. Höher zeichnet Konturen mit dünnen Streifen nach.',
  'Formarten',
  'Kommaliste aus ellipse, triangle, rectangle. Weniger Arten = stilisierterer Look.',
  'Arten-Mischung',
  'Anteil jeder Art, in derselben Reihenfolge wie die Liste darüber.',
  'Kantenbewusste Größe',
  'Verkleinert Kandidaten nahe starker Kanten. Hilft Porträts; schadet Text und flacher Grafik.',
  'Nachpassung',
  'Setzt die unnützesten Formen gegen das fertige Bild neu. Nie schlechter, kostet Zeit.',
  'Kompakte Formen bevorzugen',
  'Bestraft ausufernde Formen über zusammenhanglose Bereiche hinweg.',
  'Ausreißer-Bereinigung',
  'Entfernt Formen, deren Rand eine Kante zeichnet, die das Bild nicht hat. 0 = aus; nach Auge beurteilen.',
  'Suchraster',
  'Zellen der Platzierungssuche. Feiner trifft kleine Details, verteilt den Start dünner.',
  'Such-Preset',
  'Ein Regler für die Suchbudgets darunter. Jede editierte Zahl übersteuert ihre Stufe.',
  'Seed',
  'Gleicher Seed, gleiche Einstellungen, gleiches Ergebnis. Ändern würfelt die Komposition neu.',
  'Kandidaten pro Form',
  'Zufällige Platzierungen je Form. Mehr = bessere Treffer, langsamer.',
  'Verfeinerungsversuche',
  'Hill-Climb-Budget zum Verbessern des besten Kandidaten jeder Form.',
  'Bewertungs-Samples',
  'Pixel, die beim Bewerten eines Kandidaten abgetastet werden. Mehr = genauer, langsamer.',
  'Suchgeduld',
  'Stopp nach so vielen Formen in Folge ohne Verbesserung. Hoch = volles Budget ausschöpfen.',
  'Überzeichnen',
  'So viel mal mehr Formen erzeugen, die besten behalten. Nur für deckende Stile.',
  'Verlaufs-Boost',
  'Extra Formbudget für weiche Verläufe, damit sie ohne sichtbare Facetten rendern.',
  'Anpassung stoppen?',
  'Die bisher platzierten Formen werden verworfen.',
  'Nur {n} von {m} Formen passen — der Rest wird im Spiel verworfen. Nutze eine größere Vorlage.',
  'Bild hierher ziehen',
  'wird vorbereitet…',
  '{n} von {m} Formen',
  '{n} Formen · {b}',
  'Erneut versuchen',
  'Tastenkürzel',
  'Änderungen verwerfen?',
  'Die im Editor geänderten Formen gehen verloren.',
]);

final _es = _cat([
  'Ejecuciones',
  'ESTILO',
  'DETALLE',
  'ORIGEN',
  'Generar',
  'Exportar',
  'Inyectar',
  'Editar',
  'Recortar',
  'antes',
  'después',
  'Suelta una imagen aquí',
  'una foto, un dibujo, un logo — se convierte en formas de vinilo',
  'Elegir archivo…',
  'Elegir otro…',
  'listo — elige un estilo y un detalle, luego genera',
  'Sin imagen',
  'Construyendo formas',
  'Terminado',
  'Falló',
  'listo para inyectar',
  'Construir formas',
  'Pulir bordes',
  'Finalizar',
  'ACTIVIDAD',
  'Todo',
  'Problemas',
  'Resultados',
  'Copiar',
  'Limpiar',
  'Cerrar',
  'Hecho',
  'Restablecer',
  'Aplicar recorte',
  'Libre',
  'Plantilla',
  'Ajustes avanzados…',
  'Buscar',
  'Abrir',
  'Eliminar',
  'Nada guardado aún — cada ejecución terminada aparece aquí.',
  'Ninguna ejecución coincide.',
  'Deshacer',
  'Rehacer',
  'Guardar en ejecuciones',
  'Editando',
  'Nada seleccionado',
  'COLOR',
  'OPACIDAD',
  'CAPAS',
  'Atrás',
  'Adelante',
  'Reflejar H',
  'Reflejar V',
  'Duplicar',
  'INYECTAR EN FH6',
  'Capas de la plantilla',
  'el número exacto de capas del grupo abierto en el editor',
  'Escala',
  'Guarda y recarga el vinilo en FH6 después',
  'Escribiendo…',
  'estimando…',
  'El motor no arrancó',
  'Todas',
  'Cómo funciona',
  'Elige una imagen',
  _en['helpStep1Body']!,
  'Elige estilo y tamaño',
  _en['helpStep2Body']!,
  'Genera',
  _en['helpStep3Body']!,
  'Abre el juego',
  _en['helpStep4Body']!,
  'Transfiere',
  _en['helpStep5Body']!,
  _en['helpWarning']!,
  'Detener',
  'Ver',
  'Cancelar',
  'Cargar',
  '¿Cargar esta ejecución?',
  'Se reemplazará lo que hay ahora en el lienzo.',
  '¿Eliminar esta ejecución?',
  'Esto no se puede deshacer.',
  'Guardar estos ajustes…',
  'Mis ajustes',
  'Nombre del ajuste',
  'Guardar',
  'Ajustes avanzados',
  'Intentos por ejecución',
  'Ejecuta todo el proceso N veces y se queda con el mejor. N veces más lento.',
  'Diagnóstico',
  'Abrir la carpeta del registro',
  'Copiar la ruta',
  'Si algo falla, envía este archivo.',
  'Usar la resolución del original',
  'Ajusta a la resolución real de la imagen. Mucho más lento con originales grandes.',
  'Mantener las formas dentro de la imagen',
  'Cada forma se queda dentro de la imagen. Evita que se salgan por el borde.',
  'Modo rápido',
  'Evalúa una cuarta parte de los candidatos. Mucho más rápido, 2-6% más de error.',
  'Quitar el término de contorno',
  'Ayuda a la mitad de las imágenes y perjudica al resto. Compara a ojo.',
  'Quitar el término de bordes falsos',
  'Desactívalo cuando el resultado se vea demasiado suave.',
  'Un solo color',
  'Un color plano sobre un recorte limpio. Sin bordes grises suavizados.',
  'Modo económico',
  'Reajusta cada forma mientras construye. Mejor por debajo de 1500 formas.',
  'formas',
  'pegatina',
  'parachoques',
  'máximo',
  'o escribe un número',
  'Ajustes',
  'Sonido al terminar',
  'Un tono breve cuando las formas están listas.',
  'Parpadear en la barra de tareas',
  'Solo cuando la ventana está en segundo plano.',
  'Registro',
  'Seleccionar',
  'Editar',
  'dibujando…',
  'una imagen se convierte en formas de vinilo',
  'Motor',
  'inactivo',
  'Transferencia',
  'lista',
  'disponible, sin privilegios',
  'no disponible aquí',
  'Ejecuciones guardadas',
  'La transferencia escribe en el juego en marcha. Después guarda y recarga el vinilo: FH6 solo lo reconstruye entonces.',
  'Abrir la carpeta de la biblioteca',
  'TAMAÑO',
  'ÁNGULO',
  'quedan unos {t}',
  'Suelta aquí',
  'Elipse',
  'Rectángulo',
  'Triángulo',
  'Capa nueva',
  'Mover la forma aquí',
  'Seleccionar toda la capa',
  'Bloquear',
  'Ocultar',
  'Nombre',
  'Fecha',
  'Seleccionar',
  'Todo',
  'Ninguno',
  'Hoy',
  'Ayer',
  'Antes',
  '¿Eliminar {n} ejecuciones?',
  'Se van para siempre, con sus formas.',
  'Banco',
  'supera el límite de 3000 del juego',
  'Referencia',
  'Crear desde cero',
  'Ajuste experto',
  'Los valores propios del motor, editables. Vienen afinados; cámbialos para '
      'cambiar tiempo por calidad o buscar un estilo. Un punto marca lo modificado.',
  'Restablecer todo',
  'Suavidad y nitidez',
  'Bordes y formas',
  'Búsqueda y calidad',
  'Pulido conjunto',
  'Refina todas las formas juntas tras colocarlas. Apagado = resultado bruto: más rápido, más tosco.',
  'Iteraciones de pulido',
  'Más iteraciones asientan más bordes y colores. El tiempo crece con el número.',
  'Suavidad final de bordes',
  'Dónde termina el afilado. Menos = bordes más nítidos; más = fundidos más suaves.',
  'Formas semitransparentes',
  'Las capas translúcidas crean degradados suaves con menos formas. Apagado = todo opaco.',
  'Mínimo de opacidad',
  'Cuán transparente puede ser una forma. Más alto = más nítido, pero los degradados piden más formas.',
  'Peso del detalle',
  'Cuánto favorece el ajuste las zonas detalladas. 0 = todos los píxeles iguales.',
  'Estiramiento máx.',
  'Cuán alargada puede ser una forma. Más alto traza contornos con tiras finas.',
  'Tipos de forma',
  'Lista con comas: ellipse, triangle, rectangle. Menos tipos = aspecto más estilizado.',
  'Mezcla de tipos',
  'Proporción de cada tipo, en el mismo orden que la lista de arriba.',
  'Tamaño según bordes',
  'Encoge candidatos cerca de bordes fuertes. Ayuda a retratos; daña texto y gráficos planos.',
  'Reajuste final',
  'Recoloca las formas menos útiles contra la imagen terminada. Nunca peor, cuesta tiempo.',
  'Preferir formas compactas',
  'Penaliza formas extendidas sobre zonas sin relación.',
  'Limpieza de intrusos',
  'Quita formas cuyo borde dibuja un filo que la imagen no tiene. 0 = apagado; júzgalo a ojo.',
  'Rejilla de búsqueda',
  'Celdas de la búsqueda de colocación. Más fina apunta a detalles pequeños y reparte menos el inicio.',
  'Preset de búsqueda',
  'Un mando para los presupuestos de abajo. Cada número editado anula su nivel.',
  'Semilla',
  'Misma semilla y ajustes, mismo resultado. Cámbiala para rehacer la composición.',
  'Candidatos por forma',
  'Colocaciones aleatorias probadas por forma. Más = mejores encajes, más lento.',
  'Intentos de refinado',
  'Presupuesto de mejora del mejor candidato de cada forma.',
  'Muestras de puntuación',
  'Píxeles muestreados al puntuar un candidato. Más = puntuación más exacta, más lento.',
  'Paciencia de búsqueda',
  'Parar tras tantas formas seguidas sin mejora. Alto = gastar todo el presupuesto.',
  'Sobregeneración',
  'Genera tantas veces más formas y conserva las mejores. Solo estilos opacos.',
  'Impulso de degradados',
  'Presupuesto extra de formas para degradados suaves, sin facetas visibles.',
  '¿Detener el ajuste?',
  'Las formas colocadas hasta ahora se descartarán.',
  'Solo caben {n} de {m} formas: el resto se descartará en el juego. Usa una plantilla mayor.',
  'arrastra una imagen aquí',
  'preparando…',
  '{n} de {m} formas',
  '{n} formas · {b}',
  'Reintentar',
  'Atajos de teclado',
  '¿Descartar los cambios?',
  'Se perderán las formas que cambiaste en el editor.',
]);

final _ptBR = _cat([
  'Execuções',
  'ESTILO',
  'DETALHE',
  'ORIGEM',
  'Gerar',
  'Exportar',
  'Injetar',
  'Editar formas',
  'Recortar',
  'antes',
  'depois',
  'Solte uma imagem aqui',
  'uma foto, um desenho, uma logo — vira formas de vinil',
  'Escolher arquivo…',
  'Escolher outro…',
  'pronto — escolha um estilo e um detalhe, depois gere',
  'Sem imagem',
  'Construindo formas',
  'Concluído',
  'Falhou',
  'pronto para injetar',
  'Construir formas',
  'Polir bordas',
  'Concluir',
  'ATIVIDADE',
  'Tudo',
  'Problemas',
  'Resultados',
  'Copiar',
  'Limpar',
  'Fechar',
  'Pronto',
  'Redefinir',
  'Aplicar recorte',
  'Livre',
  'Modelo',
  'Configurações avançadas…',
  'Buscar',
  'Abrir',
  'Excluir',
  'Nada salvo ainda — toda execução concluída aparece aqui.',
  'Nenhuma execução corresponde.',
  'Desfazer',
  'Refazer',
  'Salvar nas execuções',
  'Editando',
  'Nada selecionado',
  'COR',
  'OPACIDADE',
  'CAMADAS',
  'Voltar',
  'Avançar',
  'Espelhar H',
  'Espelhar V',
  'Duplicar',
  'INJETAR NO FH6',
  'Camadas do modelo',
  'o número exato de camadas do grupo aberto no editor',
  'Escala',
  'Salve e recarregue o vinil no FH6 depois',
  'Gravando…',
  'estimando…',
  'O motor não iniciou',
  'Todas',
  'Como funciona',
  'Escolha uma imagem',
  _en['helpStep1Body']!,
  'Escolha estilo e tamanho',
  _en['helpStep2Body']!,
  'Gere',
  _en['helpStep3Body']!,
  'Abra o jogo',
  _en['helpStep4Body']!,
  'Transfira',
  _en['helpStep5Body']!,
  _en['helpWarning']!,
  'Parar',
  'Ver',
  'Cancelar',
  'Carregar',
  'Carregar esta execução?',
  'O que está na tela agora será substituído.',
  'Excluir esta execução?',
  'Isso não pode ser desfeito.',
  'Salvar estas configurações…',
  'Meus perfis',
  'Nome do perfil',
  'Salvar',
  'Configurações avançadas',
  'Tentativas por execução',
  'Roda todo o processo N vezes e fica com o melhor. N vezes mais lento.',
  'Diagnóstico',
  'Abrir a pasta do log',
  'Copiar o caminho',
  'Se algo der errado, envie este arquivo.',
  'Usar a resolução do original',
  'Ajusta na resolução real da imagem. Bem mais lento em originais grandes.',
  'Manter as formas dentro da imagem',
  'Cada forma fica dentro da imagem. Evita vazamento na borda.',
  'Modo rápido',
  'Avalia um quarto dos candidatos. Bem mais rápido, 2-6% mais erro.',
  'Remover o termo de contorno',
  'Ajuda cerca de metade das imagens e piora o resto. Compare a olho.',
  'Remover o termo de bordas falsas',
  'Desligue quando o resultado ficar macio demais.',
  'Cor única',
  'Uma cor sólida em um recorte limpo. Sem bordas cinzentas suavizadas.',
  'Modo econômico',
  'Reajusta cada forma enquanto constrói. Melhor abaixo de 1500 formas.',
  'formas',
  'adesivo',
  'para-choque',
  'máximo',
  'ou digite um número',
  'Configurações',
  'Som ao terminar',
  'Um toque curto quando as formas ficam prontas.',
  'Piscar na barra de tarefas',
  'Só quando a janela está em segundo plano.',
  'Log',
  'Selecionar',
  'Editar',
  'desenhando…',
  'uma imagem vira formas de vinil',
  'Motor',
  'ocioso',
  'Transferência',
  'pronta',
  'disponível, sem privilégios',
  'indisponível aqui',
  'Execuções salvas',
  'A transferência escreve no jogo em execução. Depois salve e recarregue o vinil — o FH6 só o reconstrói então.',
  'Abrir a pasta da biblioteca',
  'TAMANHO',
  'ÂNGULO',
  'faltam cerca de {t}',
  'Pode soltar',
  'Elipse',
  'Retângulo',
  'Triângulo',
  'Nova camada',
  'Mover a forma para cá',
  'Selecionar a camada inteira',
  'Bloquear',
  'Ocultar',
  'Nome',
  'Data',
  'Selecionar',
  'Tudo',
  'Nenhum',
  'Hoje',
  'Ontem',
  'Antes',
  'Excluir {n} execuções?',
  'Elas somem de vez, com as formas.',
  'Banco',
  'acima do limite de 3000 do jogo',
  'Referência',
  'Criar do zero',
  'Ajuste de especialista',
  'Os valores do próprio motor, editáveis. Já vêm calibrados; mude para trocar '
      'tempo por qualidade ou buscar um estilo. Um ponto marca o que foi alterado.',
  'Redefinir tudo',
  'Suavidade e nitidez',
  'Bordas e formas',
  'Busca e qualidade',
  'Polimento conjunto',
  'Refina todas as formas juntas após a colocação. Desligado = resultado bruto: mais rápido, mais áspero.',
  'Iterações de polimento',
  'Mais iterações assentam mais bordas e cores. O tempo cresce com o número.',
  'Suavidade final das bordas',
  'Onde o afiamento termina. Menor = bordas mais nítidas; maior = fusões mais suaves.',
  'Formas semitransparentes',
  'Camadas translúcidas criam degradês suaves com menos formas. Desligado = tudo opaco.',
  'Piso de opacidade',
  'Quão transparente uma forma pode ser. Maior = mais nítido, mas degradês pedem mais formas.',
  'Peso do detalhe',
  'Quanto o ajuste favorece áreas detalhadas. 0 = todos os pixels iguais.',
  'Alongamento máx.',
  'Quão alongada uma forma pode ficar. Maior traça contornos com tiras finas.',
  'Tipos de forma',
  'Lista com vírgulas: ellipse, triangle, rectangle. Menos tipos = visual mais estilizado.',
  'Mistura de tipos',
  'Proporção de cada tipo, na mesma ordem da lista acima.',
  'Tamanho ciente de bordas',
  'Encolhe candidatos perto de bordas fortes. Ajuda retratos; prejudica texto e arte chapada.',
  'Reencaixe final',
  'Recoloca as formas menos úteis contra a imagem pronta. Nunca pior, custa tempo.',
  'Preferir formas compactas',
  'Penaliza formas esparramadas por regiões sem relação.',
  'Limpeza de intrusos',
  'Remove formas cuja borda desenha um contorno que a imagem não tem. 0 = desligado; julgue no olho.',
  'Grade de busca',
  'Células da busca de colocação. Mais fina mira detalhes pequenos e espalha menos o início.',
  'Preset de busca',
  'Um controle para os orçamentos abaixo. Cada número editado passa por cima do seu nível.',
  'Semente',
  'Mesma semente e ajustes, mesmo resultado. Mude para sortear outra composição.',
  'Candidatos por forma',
  'Colocações aleatórias testadas por forma. Mais = encaixes melhores, mais lento.',
  'Tentativas de refino',
  'Orçamento de melhoria do melhor candidato de cada forma.',
  'Amostras de pontuação',
  'Pixels amostrados ao pontuar um candidato. Mais = notas mais exatas, mais lento.',
  'Paciência da busca',
  'Parar após tantas formas seguidas sem melhora. Alto = gastar todo o orçamento.',
  'Sobregeração',
  'Gera tantas vezes mais formas e guarda as melhores. Só estilos opacos.',
  'Reforço de degradês',
  'Orçamento extra de formas para degradês suaves, sem facetas visíveis.',
  'Parar o ajuste?',
  'As formas colocadas até agora serão descartadas.',
  'Apenas {n} de {m} formas cabem — o resto será descartado no jogo. Use um modelo maior.',
  'arraste uma imagem aqui',
  'preparando…',
  '{n} de {m} formas',
  '{n} formas · {b}',
  'Tentar novamente',
  'Atalhos de teclado',
  'Descartar as alterações?',
  'As formas alteradas no editor serão perdidas.',
]);

final _fr = _cat([
  'Rendus',
  'STYLE',
  'DÉTAIL',
  'SOURCE',
  'Générer',
  'Exporter',
  'Injecter',
  'Modifier',
  'Recadrer',
  'avant',
  'après',
  'Déposez une image ici',
  'une photo, un dessin, un logo — devient des formes de vinyle',
  'Choisir un fichier…',
  'En choisir une autre…',
  'prêt — choisissez un style et un détail, puis générez',
  'Aucune image',
  'Construction des formes',
  'Terminé',
  'Échec',
  'prêt à injecter',
  'Construire les formes',
  'Affiner les bords',
  'Finaliser',
  'ACTIVITÉ',
  'Tout',
  'Problèmes',
  'Résultats',
  'Copier',
  'Effacer',
  'Fermer',
  'Terminé',
  'Réinitialiser',
  'Appliquer le recadrage',
  'Libre',
  'Gabarit',
  'Réglages avancés…',
  'Rechercher',
  'Ouvrir',
  'Supprimer',
  'Rien d’enregistré — chaque rendu terminé arrive ici.',
  'Aucun rendu ne correspond.',
  'Annuler',
  'Rétablir',
  'Enregistrer dans les rendus',
  'Édition',
  'Rien de sélectionné',
  'COULEUR',
  'OPACITÉ',
  'CALQUES',
  'Reculer',
  'Avancer',
  'Miroir H',
  'Miroir V',
  'Dupliquer',
  'INJECTER DANS FH6',
  'Calques du gabarit',
  'le nombre exact de calques du groupe ouvert dans l’éditeur',
  'Échelle',
  'Enregistrez puis rechargez le vinyle dans FH6',
  'Écriture…',
  'estimation…',
  'Le moteur n’a pas démarré',
  'Tous',
  'Comment ça marche',
  'Choisir une image',
  _en['helpStep1Body']!,
  'Choisir style et taille',
  _en['helpStep2Body']!,
  'Générer',
  _en['helpStep3Body']!,
  'Ouvrir le jeu',
  _en['helpStep4Body']!,
  'Transférer',
  _en['helpStep5Body']!,
  _en['helpWarning']!,
  'Arrêter',
  'Vue',
  'Annuler',
  'Charger',
  'Charger ce rendu ?',
  'Ce qui est sur la toile sera remplacé.',
  'Supprimer ce rendu ?',
  'C’est irréversible.',
  'Enregistrer ces réglages…',
  'Mes réglages',
  'Nom du réglage',
  'Enregistrer',
  'Réglages avancés',
  'Tentatives par rendu',
  'Exécute toute la chaîne N fois et garde la meilleure. N fois plus lent.',
  'Diagnostic',
  'Ouvrir le dossier du journal',
  'Copier le chemin',
  'En cas de problème, envoyez ce fichier.',
  'Utiliser la résolution source',
  'Calcule à la résolution réelle de l\'image. Bien plus lent sur les grandes sources.',
  'Garder les formes dans l\'image',
  'Chaque forme reste dans l\'image. Évite les débordements sur les bords.',
  'Mode rapide',
  'Évalue un quart des candidats. Bien plus rapide, 2-6% d’erreur en plus.',
  'Retirer le terme de contour',
  'Aide environ la moitié des images et dessert les autres. Comparez à l’œil.',
  'Retirer le terme de faux bords',
  'À désactiver quand le résultat paraît trop doux.',
  'Couleur unique',
  'Une seule couleur pleine sur un détourage net. Pas de bords gris lissés.',
  'Mode économique',
  'Réajuste chaque forme au fur et à mesure. Idéal en dessous de 1500 formes.',
  'formes',
  'autocollant',
  'pare-chocs',
  'maximum',
  'ou saisissez un nombre',
  'Réglages',
  'Son à la fin',
  'Un bref signal quand les formes sont prêtes.',
  'Faire clignoter la barre des tâches',
  'Seulement quand la fenêtre est en arrière-plan.',
  'Journal',
  'Sélection',
  'Modifier',
  'rendu en cours…',
  'une image devient des formes en vinyle',
  'Moteur',
  'au repos',
  'Transfert',
  'prêt',
  'disponible, sans privilèges',
  'indisponible ici',
  'Rendus enregistrés',
  'Le transfert écrit dans le jeu en cours. Enregistrez puis rechargez le vinyle ensuite — FH6 ne le reconstruit qu’à ce moment.',
  'Ouvrir le dossier de la bibliothèque',
  'TAILLE',
  'ANGLE',
  'environ {t} restantes',
  'Lâchez ici',
  'Ellipse',
  'Rectangle',
  'Triangle',
  'Nouveau calque',
  'Déplacer la forme ici',
  'Sélectionner tout le calque',
  'Verrouiller',
  'Masquer',
  'Nom',
  'Date',
  'Sélectionner',
  'Tout',
  'Aucun',
  'Aujourd’hui',
  'Hier',
  'Avant',
  'Supprimer {n} rendus ?',
  'Ils partent définitivement, avec leurs formes.',
  'Banque',
  'au-delà de la limite de 3000 du jeu',
  'Référence',
  'Créer à partir de zéro',
  'Réglage expert',
  'Les valeurs propres du moteur, modifiables. Elles sont déjà calibrées ; '
      'changez-les pour échanger du temps contre de la qualité ou chercher un '
      'style. Un point marque ce qui a été modifié.',
  'Tout réinitialiser',
  'Douceur et netteté',
  'Bords et formes',
  'Recherche et qualité',
  'Polissage conjoint',
  'Affine toutes les formes ensemble après le placement. Désactivé = résultat brut : plus rapide, plus grossier.',
  'Itérations de polissage',
  'Plus d’itérations posent davantage bords et couleurs. Le temps croît avec le nombre.',
  'Douceur finale des bords',
  'Où s’arrête l’affûtage. Plus bas = bords plus nets ; plus haut = fondus plus doux.',
  'Formes semi-transparentes',
  'Les couches translucides créent des dégradés doux avec moins de formes. Désactivé = tout opaque.',
  'Plancher d’opacité',
  'Transparence maximale d’une forme. Plus haut = plus net, mais les dégradés demandent plus de formes.',
  'Poids du détail',
  'À quel point l’ajustement favorise les zones détaillées. 0 = tous les pixels égaux.',
  'Étirement max.',
  'Allongement maximal d’une forme. Plus haut trace les contours en fines bandes.',
  'Types de forme',
  'Liste séparée par virgules : ellipse, triangle, rectangle. Moins de types = rendu plus stylisé.',
  'Mélange des types',
  'Part de chaque type, dans le même ordre que la liste ci-dessus.',
  'Taille selon les bords',
  'Réduit les candidats près des bords forts. Aide les portraits ; nuit au texte et aux aplats.',
  'Réajustement final',
  'Replace les formes les moins utiles face à l’image finie. Jamais pire, coûte du temps.',
  'Préférer les formes compactes',
  'Pénalise les formes étalées sur des zones sans rapport.',
  'Nettoyage des intrus',
  'Retire les formes dont le bord dessine une arête absente de l’image. 0 = désactivé ; jugez à l’œil.',
  'Grille de recherche',
  'Cellules de la recherche de placement. Plus fine vise les petits détails, disperse moins le départ.',
  'Préréglage de recherche',
  'Un seul réglage pour les budgets ci-dessous. Tout nombre modifié prime sur son palier.',
  'Graine',
  'Même graine, mêmes réglages, même résultat. Changez-la pour retirer la composition.',
  'Candidats par forme',
  'Placements aléatoires essayés par forme. Plus = meilleurs ajustements, plus lent.',
  'Essais d’affinage',
  'Budget d’amélioration du meilleur candidat de chaque forme.',
  'Échantillons de score',
  'Pixels échantillonnés pour noter un candidat. Plus = scores plus exacts, plus lent.',
  'Patience de recherche',
  'Arrêt après tant de formes de suite sans progrès. Élevé = dépenser tout le budget.',
  'Surgénération',
  'Génère autant de fois plus de formes et garde les meilleures. Styles opaques uniquement.',
  'Renfort des dégradés',
  'Budget de formes en plus pour les dégradés doux, sans facettes visibles.',
  'Arrêter l\'ajustement ?',
  'Les formes déjà placées seront abandonnées.',
  'Seules {n} formes sur {m} tiennent — le reste sera ignoré dans le jeu. Utilisez un gabarit plus grand.',
  'déposez une image ici',
  'préparation…',
  '{n} formes sur {m}',
  '{n} formes · {b}',
  'Réessayer',
  'Raccourcis clavier',
  'Abandonner les modifications ?',
  'Les formes modifiées dans l\'éditeur seront perdues.',
]);

final _pl = _cat([
  'Przebiegi',
  'STYL',
  'SZCZEGÓŁ',
  'ŹRÓDŁO',
  'Generuj',
  'Eksport',
  'Wstrzyknij',
  'Edytuj',
  'Przytnij',
  'przed',
  'po',
  'Upuść obraz tutaj',
  'zdjęcie, rysunek, logo — stanie się kształtami winylu',
  'Wybierz plik…',
  'Wybierz inny…',
  'gotowe — wybierz styl i szczegół, potem generuj',
  'Brak obrazu',
  'Buduję kształty',
  'Gotowe',
  'Błąd',
  'gotowe do wstrzyknięcia',
  'Budowa kształtów',
  'Wygładzanie krawędzi',
  'Zakończenie',
  'AKTYWNOŚĆ',
  'Wszystko',
  'Problemy',
  'Wyniki',
  'Kopiuj',
  'Wyczyść',
  'Zamknij',
  'Gotowe',
  'Resetuj',
  'Zastosuj przycięcie',
  'Dowolnie',
  'Szablon',
  'Ustawienia zaawansowane…',
  'Szukaj',
  'Otwórz',
  'Usuń',
  'Nic jeszcze nie zapisano — każdy ukończony przebieg trafia tutaj.',
  'Nic nie pasuje.',
  'Cofnij',
  'Ponów',
  'Zapisz w przebiegach',
  'Edycja',
  'Nic nie zaznaczono',
  'KOLOR',
  'KRYCIE',
  'WARSTWY',
  'Wstecz',
  'Naprzód',
  'Odbij poziomo',
  'Odbij pionowo',
  'Duplikuj',
  'WSTRZYKNIJ DO FH6',
  'Warstwy szablonu',
  'dokładna liczba warstw grupy otwartej w edytorze',
  'Skala',
  'Potem zapisz i przeładuj winyl w FH6',
  'Zapisuję…',
  'szacuję…',
  'Silnik nie wystartował',
  'Wszystkie',
  'Jak to działa',
  'Wybierz obraz',
  _en['helpStep1Body']!,
  'Wybierz styl i rozmiar',
  _en['helpStep2Body']!,
  'Generuj',
  _en['helpStep3Body']!,
  'Otwórz grę',
  _en['helpStep4Body']!,
  'Przenieś',
  _en['helpStep5Body']!,
  _en['helpWarning']!,
  'Zatrzymaj',
  'Podgląd',
  'Anuluj',
  'Wczytaj',
  'Wczytać ten przebieg?',
  'To, co jest teraz na płótnie, zostanie zastąpione.',
  'Usunąć ten przebieg?',
  'Tego nie da się cofnąć.',
  'Zapisz te ustawienia…',
  'Moje ustawienia',
  'Nazwa ustawienia',
  'Zapisz',
  'Ustawienia zaawansowane',
  'Prób na przebieg',
  'Uruchamia cały proces N razy i zachowuje najlepszy wynik. N razy wolniej.',
  'Diagnostyka',
  'Otwórz folder z logiem',
  'Kopiuj ścieżkę',
  'Jeśli coś pójdzie nie tak, wyślij ten plik.',
  'Użyj rozdzielczości oryginału',
  'Dopasowuje w prawdziwej rozdzielczości obrazu. Przy dużych plikach znacznie wolniej.',
  'Trzymaj kształty w obrazie',
  'Każdy kształt zostaje w obrazie. Zapobiega wychodzeniu poza krawędź.',
  'Tryb szybki',
  'Ocenia jedną czwartą kandydatów. Znacznie szybciej, o 2-6% większy błąd.',
  'Usuń człon konturowy',
  'Mniej więcej połowie obrazów pomaga, reszcie szkodzi. Porównaj okiem.',
  'Usuń człon fałszywych krawędzi',
  'Wyłącz, gdy wynik wygląda zbyt miękko.',
  'Jeden kolor',
  'Jeden pełny kolor na czystym wycinku. Bez szarych wygładzonych krawędzi.',
  'Tryb oszczędny',
  'Dopasowuje każdy kształt na bieżąco. Najlepiej poniżej 1500 kształtów.',
  'kształtów',
  'naklejka',
  'zderzak',
  'maksimum',
  'albo wpisz liczbę',
  'Ustawienia',
  'Dźwięk po zakończeniu',
  'Krótki sygnał, gdy kształty są gotowe.',
  'Migaj na pasku zadań',
  'Tylko gdy okno jest w tle.',
  'Dziennik',
  'Zaznacz',
  'Edytuj',
  'rysowanie…',
  'obraz staje się kształtami winylu',
  'Silnik',
  'bezczynny',
  'Przeniesienie',
  'gotowe',
  'dostępne, bez uprawnień',
  'tutaj niedostępne',
  'Zapisane przebiegi',
  'Przeniesienie zapisuje do działającej gry. Potem zapisz i wczytaj winyl ponownie — FH6 przebudowuje go dopiero wtedy.',
  'Otwórz folder biblioteki',
  'ROZMIAR',
  'KĄT',
  'zostało około {t}',
  'Upuść tutaj',
  'Elipsa',
  'Prostokąt',
  'Trójkąt',
  'Nowa warstwa',
  'Przenieś kształt tutaj',
  'Zaznacz całą warstwę',
  'Zablokuj',
  'Ukryj',
  'Nazwa',
  'Data',
  'Zaznacz',
  'Wszystko',
  'Nic',
  'Dziś',
  'Wczoraj',
  'Wcześniej',
  'Usunąć przebiegi: {n}?',
  'Znikną na zawsze, razem z kształtami.',
  'Bank',
  'ponad limit gry 3000',
  'Oryginał',
  'Utwórz od zera',
  'Strojenie eksperckie',
  'Własne wartości silnika, do edycji. Fabrycznie zestrojone; zmieniaj, by '
      'wymienić czas na jakość albo szukać własnego stylu. Kropka oznacza zmienione.',
  'Zresetuj wszystko',
  'Gładkość i ostrość',
  'Krawędzie i kształty',
  'Wyszukiwanie i jakość',
  'Wspólne szlifowanie',
  'Dopracowuje wszystkie kształty razem po rozmieszczeniu. Wył. = surowy wynik: szybciej, zgrubniej.',
  'Iteracje szlifu',
  'Więcej iteracji mocniej osadza krawędzie i kolory. Czas rośnie z liczbą.',
  'Końcowa miękkość krawędzi',
  'Gdzie kończy się wyostrzanie. Mniej = ostrzejsze krawędzie; więcej = łagodniejsze przejścia.',
  'Kształty półprzezroczyste',
  'Przezroczyste warstwy budują gładkie gradienty mniejszą liczbą kształtów. Wył. = wszystko kryjące.',
  'Próg krycia',
  'Jak przezroczysty może być kształt. Wyżej = ostrzej, ale gradienty potrzebują więcej kształtów.',
  'Waga detalu',
  'Jak mocno dopasowanie faworyzuje szczegółowe obszary. 0 = wszystkie piksele równe.',
  'Maks. wydłużenie',
  'Jak wydłużony może być kształt. Wyżej rysuje kontury cienkimi paskami.',
  'Rodzaje kształtów',
  'Lista po przecinku: ellipse, triangle, rectangle. Mniej rodzajów = bardziej stylizowany wygląd.',
  'Proporcje rodzajów',
  'Udział każdego rodzaju, w kolejności listy powyżej.',
  'Rozmiar przy krawędziach',
  'Zmniejsza kandydatów przy mocnych krawędziach. Pomaga portretom; szkodzi tekstowi i płaskiej grafice.',
  'Dopasowanie końcowe',
  'Przestawia najmniej przydatne kształty względem gotowego obrazu. Nigdy gorzej, kosztuje czas.',
  'Preferuj zwarte kształty',
  'Karze rozlazłe kształty ciągnące się przez niepowiązane obszary.',
  'Czyszczenie odstających',
  'Usuwa kształty, których obwódka rysuje krawędź nieobecną na obrazie. 0 = wył.; oceniaj okiem.',
  'Siatka wyszukiwania',
  'Komórki wyszukiwania rozmieszczenia. Drobniejsza celuje w małe detale, rzadziej rozrzuca start.',
  'Preset wyszukiwania',
  'Jedno pokrętło dla budżetów poniżej. Każda zmieniona liczba nadpisuje swój poziom.',
  'Ziarno',
  'To samo ziarno i ustawienia — ten sam wynik. Zmień, by przelosować kompozycję.',
  'Kandydatów na kształt',
  'Losowe rozmieszczenia próbowane dla każdego kształtu. Więcej = lepsze dopasowania, wolniej.',
  'Próby dopracowania',
  'Budżet wspinaczki poprawiający najlepszego kandydata kształtu.',
  'Próbki oceny',
  'Piksele próbkowane przy ocenie kandydata. Więcej = dokładniej, wolniej.',
  'Cierpliwość wyszukiwania',
  'Stop po tylu kształtach z rzędu bez poprawy. Dużo = wydać cały budżet.',
  'Nadprodukcja',
  'Generuje tyle razy więcej kształtów i zachowuje najlepsze. Tylko style kryjące.',
  'Wzmocnienie gradientów',
  'Dodatkowy budżet kształtów dla gładkich gradientów, bez widocznych faset.',
  'Zatrzymać dopasowanie?',
  'Dotychczas umieszczone kształty zostaną odrzucone.',
  'Mieści się tylko {n} z {m} kształtów — reszta zostanie odrzucona w grze. Użyj większego szablonu.',
  'przeciągnij tu obraz',
  'przygotowywanie…',
  '{n} z {m} kształtów',
  '{n} kształtów · {b}',
  'Spróbuj ponownie',
  'Skróty klawiszowe',
  'Odrzucić zmiany?',
  'Kształty zmienione w edytorze zostaną utracone.',
]);

final _it = _cat([
  'Esecuzioni',
  'STILE',
  'DETTAGLIO',
  'ORIGINE',
  'Genera',
  'Esporta',
  'Inietta',
  'Modifica',
  'Ritaglia',
  'prima',
  'dopo',
  'Trascina qui un’immagine',
  'una foto, un disegno, un logo — diventa forme in vinile',
  'Scegli file…',
  'Scegline un’altra…',
  'pronto — scegli stile e dettaglio, poi genera',
  'Nessuna immagine',
  'Costruzione forme',
  'Completato',
  'Fallito',
  'pronto per l’iniezione',
  'Costruisci forme',
  'Rifinisci bordi',
  'Completa',
  'ATTIVITÀ',
  'Tutto',
  'Problemi',
  'Risultati',
  'Copia',
  'Pulisci',
  'Chiudi',
  'Fatto',
  'Reimposta',
  'Applica ritaglio',
  'Libero',
  'Modello',
  'Impostazioni avanzate…',
  'Cerca',
  'Apri',
  'Elimina',
  'Ancora nulla — ogni esecuzione completata finisce qui.',
  'Nessuna esecuzione corrisponde.',
  'Annulla',
  'Ripeti',
  'Salva nelle esecuzioni',
  'Modifica',
  'Nulla selezionato',
  'COLORE',
  'OPACITÀ',
  'LIVELLI',
  'Indietro',
  'Avanti',
  'Specchia O',
  'Specchia V',
  'Duplica',
  'INIETTA IN FH6',
  'Livelli del modello',
  'il numero esatto di livelli del gruppo aperto nell’editor',
  'Scala',
  'Poi salva e ricarica il vinile in FH6',
  'Scrittura…',
  'stima…',
  'Il motore non è partito',
  'Tutte',
  'Come funziona',
  'Scegli un’immagine',
  _en['helpStep1Body']!,
  'Scegli stile e dimensione',
  _en['helpStep2Body']!,
  'Genera',
  _en['helpStep3Body']!,
  'Apri il gioco',
  _en['helpStep4Body']!,
  'Trasferisci',
  _en['helpStep5Body']!,
  _en['helpWarning']!,
  'Ferma',
  'Vista',
  'Annulla',
  'Carica',
  'Caricare questa esecuzione?',
  'Ciò che è ora sulla tela verrà sostituito.',
  'Eliminare questa esecuzione?',
  'L’operazione non è reversibile.',
  'Salva queste impostazioni…',
  'Le mie impostazioni',
  'Nome',
  'Salva',
  'Impostazioni avanzate',
  'Tentativi per esecuzione',
  'Esegue l’intera pipeline N volte e tiene il risultato migliore. N volte più lento.',
  'Diagnostica',
  'Apri la cartella del log',
  'Copia il percorso',
  'Se qualcosa non va, invia questo file.',
  'Usa la risoluzione originale',
  'Elabora alla risoluzione reale dell\'immagine. Molto più lento su sorgenti grandi.',
  'Tieni le forme dentro l\'immagine',
  'Ogni forma resta dentro l\'immagine. Evita le fuoriuscite dai bordi.',
  'Modalità rapida',
  'Valuta un quarto dei candidati. Molto più veloce, 2-6% di errore in più.',
  'Togli il termine di contorno',
  'Aiuta circa metà delle immagini e penalizza le altre. Confronta a occhio.',
  'Togli il termine dei falsi bordi',
  'Disattivalo quando il risultato sembra troppo morbido.',
  'Colore unico',
  'Un solo colore pieno su un ritaglio pulito. Nessun bordo grigio sfumato.',
  'Modalità economica',
  'Riadatta ogni forma mentre costruisce. Meglio sotto le 1500 forme.',
  'forme',
  'adesivo',
  'paraurti',
  'massimo',
  'oppure scrivi un numero',
  'Impostazioni',
  'Suono al termine',
  'Un breve segnale quando le forme sono pronte.',
  'Lampeggia nella barra delle applicazioni',
  'Solo quando la finestra è in secondo piano.',
  'Registro',
  'Seleziona',
  'Modifica',
  'disegno…',
  'un’immagine diventa forme in vinile',
  'Motore',
  'inattivo',
  'Trasferimento',
  'pronto',
  'disponibile, senza privilegi',
  'non disponibile qui',
  'Esecuzioni salvate',
  'Il trasferimento scrive nel gioco in esecuzione. Poi salva e ricarica il vinile — FH6 lo ricostruisce solo allora.',
  'Apri la cartella della libreria',
  'DIMENSIONE',
  'ANGOLO',
  'restano circa {t}',
  'Rilascia qui',
  'Ellisse',
  'Rettangolo',
  'Triangolo',
  'Nuovo livello',
  'Sposta la forma qui',
  'Seleziona tutto il livello',
  'Blocca',
  'Nascondi',
  'Nome',
  'Data',
  'Seleziona',
  'Tutto',
  'Nessuno',
  'Oggi',
  'Ieri',
  'Prima',
  'Eliminare {n} esecuzioni?',
  'Spariscono per sempre, con le loro forme.',
  'Banca',
  'oltre il limite di 3000 del gioco',
  'Riferimento',
  'Crea da zero',
  'Regolazione esperta',
  'I valori propri del motore, modificabili. Arrivano già tarati; cambiali per '
      'scambiare tempo con qualità o cercare uno stile. Un punto segna ciò che hai cambiato.',
  'Ripristina tutto',
  'Morbidezza e nitidezza',
  'Bordi e forme',
  'Ricerca e qualità',
  'Rifinitura congiunta',
  'Rifinisce tutte le forme insieme dopo il posizionamento. Spento = risultato grezzo: più veloce, più ruvido.',
  'Iterazioni di rifinitura',
  'Più iterazioni assestano di più bordi e colori. Il tempo cresce col numero.',
  'Morbidezza finale dei bordi',
  'Dove finisce l’affilatura. Più basso = bordi più netti; più alto = fusioni più morbide.',
  'Forme semitrasparenti',
  'Strati traslucidi creano sfumature morbide con meno forme. Spento = tutto opaco.',
  'Soglia di opacità',
  'Quanto trasparente può essere una forma. Più alto = più netto, ma le sfumature chiedono più forme.',
  'Peso del dettaglio',
  'Quanto l’adattamento favorisce le zone dettagliate. 0 = tutti i pixel uguali.',
  'Allungamento max',
  'Quanto può allungarsi una forma. Più alto traccia i contorni con strisce sottili.',
  'Tipi di forma',
  'Elenco separato da virgole: ellipse, triangle, rectangle. Meno tipi = look più stilizzato.',
  'Mix dei tipi',
  'Quota di ogni tipo, nello stesso ordine dell’elenco sopra.',
  'Dimensione sensibile ai bordi',
  'Riduce i candidati vicino ai bordi forti. Aiuta i ritratti; danneggia testo e grafica piatta.',
  'Riadattamento finale',
  'Ricolloca le forme meno utili contro l’immagine finita. Mai peggio, costa tempo.',
  'Preferisci forme compatte',
  'Penalizza forme sparse su zone senza relazione.',
  'Pulizia degli estranei',
  'Rimuove le forme il cui bordo disegna uno spigolo che l’immagine non ha. 0 = spento; giudica a occhio.',
  'Griglia di ricerca',
  'Celle della ricerca di posizionamento. Più fine punta ai piccoli dettagli, disperde meno l’avvio.',
  'Preset di ricerca',
  'Una manopola per i budget qui sotto. Ogni numero modificato scavalca il suo livello.',
  'Seme',
  'Stesso seme e impostazioni, stesso risultato. Cambialo per rimescolare la composizione.',
  'Candidati per forma',
  'Posizionamenti casuali provati per ogni forma. Di più = incastri migliori, più lento.',
  'Tentativi di rifinitura',
  'Budget di miglioramento del miglior candidato di ogni forma.',
  'Campioni di punteggio',
  'Pixel campionati nel valutare un candidato. Di più = punteggi più esatti, più lento.',
  'Pazienza della ricerca',
  'Stop dopo tante forme di fila senza miglioramento. Alto = spendere tutto il budget.',
  'Sovragenerazione',
  'Genera tante volte più forme e tiene le migliori. Solo stili opachi.',
  'Spinta alle sfumature',
  'Budget extra di forme per sfumature morbide, senza faccette visibili.',
  'Interrompere l\'elaborazione?',
  'Le forme posizionate finora verranno scartate.',
  'Solo {n} forme su {m} entrano — il resto verrà scartato nel gioco. Usa un modello più grande.',
  'trascina qui un\'immagine',
  'preparazione…',
  '{n} di {m} forme',
  '{n} forme · {b}',
  'Riprova',
  'Scorciatoie da tastiera',
  'Scartare le modifiche?',
  'Le forme modificate nell\'editor andranno perse.',
]);

final _tr = _cat([
  'Çalışmalar',
  'STİL',
  'AYRINTI',
  'KAYNAK',
  'Oluştur',
  'Dışa aktar',
  'Enjekte et',
  'Şekilleri düzenle',
  'Kırp',
  'önce',
  'sonra',
  'Buraya bir görsel bırakın',
  'fotoğraf, çizim, logo — vinil şekillere dönüşür',
  'Dosya seç…',
  'Başkasını seç…',
  'hazır — stil ve ayrıntı seçin, sonra oluşturun',
  'Görsel yok',
  'Şekiller oluşturuluyor',
  'Bitti',
  'Başarısız',
  'enjekte edilmeye hazır',
  'Şekilleri oluştur',
  'Kenarları düzelt',
  'Tamamla',
  'ETKİNLİK',
  'Tümü',
  'Sorunlar',
  'Sonuçlar',
  'Kopyala',
  'Temizle',
  'Kapat',
  'Tamam',
  'Sıfırla',
  'Kırpmayı uygula',
  'Serbest',
  'Şablon',
  'Gelişmiş ayarlar…',
  'Ara',
  'Aç',
  'Sil',
  'Henüz kayıt yok — biten her çalışma buraya gelir.',
  'Eşleşen çalışma yok.',
  'Geri al',
  'Yinele',
  'Çalışmalara kaydet',
  'Düzenleme',
  'Hiçbir şey seçilmedi',
  'RENK',
  'SAYDAMLIK',
  'KATMANLAR',
  'Geri',
  'İleri',
  'Yatay yansıt',
  'Dikey yansıt',
  'Çoğalt',
  'FH6’YA ENJEKTE',
  'Şablon katmanları',
  'düzenleyicide açık grubun tam katman sayısı',
  'Ölçek',
  'Sonra vinili FH6’da kaydedip yeniden yükleyin',
  'Yazılıyor…',
  'tahmin ediliyor…',
  'Motor başlamadı',
  'Tümü',
  'Nasıl çalışır',
  'Bir görsel seçin',
  _en['helpStep1Body']!,
  'Stil ve boyut seçin',
  _en['helpStep2Body']!,
  'Oluşturun',
  _en['helpStep3Body']!,
  'Oyunu açın',
  _en['helpStep4Body']!,
  'Aktarın',
  _en['helpStep5Body']!,
  _en['helpWarning']!,
  'Durdur',
  'Görünüm',
  'Vazgeç',
  'Yükle',
  'Bu çalışma yüklensin mi?',
  'Tuvalde şu an olan şey değiştirilecek.',
  'Bu çalışma silinsin mi?',
  'Bu geri alınamaz.',
  'Bu ayarları kaydet…',
  'Ayarlarım',
  'Ayar adı',
  'Kaydet',
  'Gelişmiş ayarlar',
  'Çalışma başına deneme',
  'Tüm süreci N kez çalıştırır ve en iyisini tutar. N kat yavaş.',
  'Tanılama',
  'Günlük klasörünü aç',
  'Yolu kopyala',
  'Bir şeyler ters giderse bu dosyayı gönderin.',
  'Kaynak çözünürlüğünü kullan',
  'Görselin gerçek çözünürlüğünde çalışır. Büyük kaynaklarda çok daha yavaş.',
  'Şekilleri görselin içinde tut',
  'Her şekil görselin içinde kalır. Kenardan taşmayı önler.',
  'Hızlı mod',
  'Adayların dörtte birini değerlendirir. Çok daha hızlı, %2-6 daha fazla hata.',
  'Kontur terimini çıkar',
  'Görsellerin yaklaşık yarısına yarar, kalanına zarar verir. Gözle karşılaştırın.',
  'Sahte kenar terimini çıkar',
  'Sonuç fazla yumuşak görünüyorsa kapatın.',
  'Tek renk',
  'Temiz bir kesim üzerinde tek düz renk. Gri yumuşatılmış kenar yok.',
  'Tasarruflu mod',
  'Her şekli oluştururken yeniden uyarlar. 1500 şeklin altında en iyisi.',
  'sekil',
  'cikartma',
  'tampon',
  'azami',
  'ya da bir sayi yazin',
  'Ayarlar',
  'Bitince ses cal',
  'Sekiller hazir oldugunda kisa bir uyari sesi.',
  'Gorev cubugunda yanip sonsun',
  'Yalnizca pencere arka plandayken.',
  'Gunluk',
  'Sec',
  'Duzenle',
  'ciziliyor…',
  'bir goruntu vinil sekillere donusur',
  'Motor',
  'bosta',
  'Aktarim',
  'hazir',
  'var, yonetici yetkisi yok',
  'burada yok',
  'Kayitli calismalar',
  'Aktarim calisan oyuna yazar. Sonrasinda vinili kaydedip yeniden yukleyin — FH6 onu ancak o zaman yeniden olusturur.',
  'Kitaplik klasorunu ac',
  'BOYUT',
  'ACI',
  'yaklasik {t} kaldi',
  'Birakin',
  'Elips',
  'Dikdortgen',
  'Ucgen',
  'Yeni katman',
  'Sekli buraya tasi',
  'Tum katmani sec',
  'Kilitle',
  'Gizle',
  'Ad',
  'Tarih',
  'Sec',
  'Tumu',
  'Hicbiri',
  'Bugun',
  'Dun',
  'Daha once',
  '{n} calisma silinsin mi?',
  'Sekilleriyle birlikte tamamen gider.',
  'Banka',
  'oyunun 3000 sinirinin uzerinde',
  'Referans',
  'Sifirdan olustur',
  'Uzman ayarı',
  'Motorun kendi değerleri, düzenlenebilir. Ayarlı gelirler; süreyi kaliteyle '
      'takas etmek ya da bir görünüş aramak için değiştirin. Nokta, değişeni gösterir.',
  'Tümünü sıfırla',
  'Pürüzsüzlük ve keskinlik',
  'Kenarlar ve şekiller',
  'Arama ve kalite',
  'Ortak parlatma',
  'Yerleştirmeden sonra tüm şekilleri birlikte inceltir. Kapalı = ham sonuç: daha hızlı, daha kaba.',
  'Parlatma yinelemeleri',
  'Daha çok yineleme kenarları ve renkleri daha çok oturtur. Süre sayıyla büyür.',
  'Son kenar yumuşaklığı',
  'Keskinleştirmenin bittiği yer. Düşük = daha keskin kenarlar; yüksek = daha yumuşak geçişler.',
  'Yarı saydam şekiller',
  'Saydam katmanlar daha az şekille pürüzsüz geçişler kurar. Kapalı = her şekil opak.',
  'Opaklık tabanı',
  'Bir şeklin olabileceği en saydam düzey. Yüksek = daha keskin, ama geçişler daha çok şekil ister.',
  'Ayrıntı ağırlığı',
  'Uydurmanın ayrıntılı alanları ne kadar kayırdığı. 0 = tüm pikseller eşit.',
  'Azami uzama',
  'Bir şeklin ne kadar uzayabileceği. Yüksek, konturları ince şeritlerle izler.',
  'Şekil türleri',
  'Virgüllü liste: ellipse, triangle, rectangle. Daha az tür = daha stilize görünüm.',
  'Tür karışımı',
  'Her türün payı, yukarıdaki listeyle aynı sırada.',
  'Kenara duyarlı boyut',
  'Güçlü kenarların yanında adayları küçültür. Portrelere yarar; metne ve düz grafiğe zarar verir.',
  'Son oturtma',
  'En az yararlı şekilleri bitmiş resme göre yeniden yerleştirir. Asla daha kötü olmaz, zaman alır.',
  'Derli toplu şekilleri yeğle',
  'İlgisiz bölgelere yayılan şekilleri cezalandırır.',
  'Sırıtan şekil temizliği',
  'Kenarı resimde olmayan bir çizgi çizen şekilleri kaldırır. 0 = kapalı; sonucu gözle değerlendirin.',
  'Arama ızgarası',
  'Yerleştirme aramasının hücreleri. İncesi küçük ayrıntılara nişan alır, başlangıcı daha az dağıtır.',
  'Arama ön ayarı',
  'Alttaki arama bütçeleri için tek düğme. Düzenlenen her sayı kendi kademesini ezer.',
  'Tohum',
  'Aynı tohum, aynı ayarlar, aynı sonuç. Kompozisyonu yeniden karmak için değiştirin.',
  'Şekil başına aday',
  'Her şekil için denenen rastgele yerleşimler. Çok = daha iyi oturur, daha yavaş.',
  'İnceltme denemeleri',
  'Her şeklin en iyi adayını iyileştiren tırmanış bütçesi.',
  'Puanlama örnekleri',
  'Bir adayı puanlarken örneklenen pikseller. Çok = daha kesin puan, daha yavaş.',
  'Arama sabrı',
  'Arka arkaya bu kadar şekil iyileşme getirmeyince dur. Yüksek = bütçenin tamamını harca.',
  'Fazla üretim',
  'Bu kat kadar fazla şekil üretir, en iyilerini tutar. Yalnız opak stiller.',
  'Geçiş desteği',
  'Pürüzsüz geçişler görünür yüzeyciklere bölünmesin diye ek şekil bütçesi.',
  'İşlem durdurulsun mu?',
  'Şu ana kadar yerleştirilen şekiller atılacak.',
  '{m} şekilden yalnızca {n} tanesi sığıyor — kalanı oyunda atılacak. Daha büyük bir şablon kullanın.',
  'buraya bir görsel bırakın',
  'hazırlanıyor…',
  '{m} şekilden {n} tanesi',
  '{n} şekil · {b}',
  'Yeniden dene',
  'Klavye kısayolları',
  'Değişiklikler atılsın mı?',
  'Düzenleyicide yaptığınız değişiklikler kaybolacak.',
]);

final _zhCN = _cat([
  '生成记录',
  '风格',
  '细节',
  '来源',
  '生成',
  '导出',
  '注入',
  '编辑',
  '裁剪',
  '之前',
  '之后',
  '把图片拖到这里',
  '照片、画作、标志 — 都会变成乙烯基形状',
  '选择文件…',
  '换一个…',
  '就绪 — 选好风格和细节，然后生成',
  '没有图片',
  '正在构建形状',
  '完成',
  '失败',
  '可以注入了',
  '构建形状',
  '打磨边缘',
  '收尾',
  '活动',
  '全部',
  '问题',
  '结果',
  '复制',
  '清空',
  '关闭',
  '完成',
  '重置',
  '应用裁剪',
  '自由',
  '模板',
  '高级设置…',
  '搜索',
  '打开',
  '删除',
  '还没有保存 — 每次完成的生成都会出现在这里。',
  '没有匹配的记录。',
  '撤销',
  '重做',
  '保存到生成记录',
  '编辑中',
  '未选择任何对象',
  '颜色',
  '不透明度',
  '图层',
  '下移',
  '上移',
  '水平镜像',
  '垂直镜像',
  '复制一份',
  '注入到 FH6',
  '模板图层数',
  '编辑器中打开的那个组的确切图层数',
  '缩放',
  '之后请在 FH6 中保存并重新加载贴纸',
  '正在写入…',
  '估算中…',
  '引擎未启动',
  '全部',
  '使用方法',
  '选择图片',
  _en['helpStep1Body']!,
  '选择风格和大小',
  _en['helpStep2Body']!,
  '生成',
  _en['helpStep3Body']!,
  '打开游戏',
  _en['helpStep4Body']!,
  '传送过去',
  _en['helpStep5Body']!,
  _en['helpWarning']!,
  '停止',
  '查看',
  '取消',
  '载入',
  '载入这次生成？',
  '画布上当前的内容将被替换。',
  '删除这次生成？',
  '此操作无法撤销。',
  '保存这些设置…',
  '我的预设',
  '预设名称',
  '保存',
  '高级设置',
  '每次生成的尝试次数',
  '将整个流程运行 N 次并保留最好的结果，耗时也是 N 倍。',
  '诊断',
  '打开日志文件夹',
  '复制路径',
  '如果出了问题，请发送这个文件。',
  '使用原图分辨率',
  '按图片的真实分辨率拟合。大图会慢很多。',
  '让形状留在图内',
  '每个形状都留在画面内，避免溢出边缘。',
  '快速模式',
  '只评估四分之一的候选。快得多，误差多 2-6%。',
  '去掉轮廓项',
  '大约一半的图会变好，另一半会变差。请用眼睛比较。',
  '去掉伪边缘项',
  '当结果显得太柔时关掉它。',
  '单一颜色',
  '在干净的抠图上用一种纯色，没有灰色的抗锯齿边。',
  '节省模式',
  '一边构建一边重新拟合每个形状。1500 个形状以下效果最好。',
  '个形状',
  '贴纸',
  '保险杠',
  '最大',
  '或直接输入数量',
  '设置',
  '完成时播放提示音',
  '形状生成完毕时响一声。',
  '完成时闪烁任务栏',
  '仅当窗口在后台时。',
  '日志',
  '选择',
  '编辑',
  '绘制中…',
  '把图片变成乙烯贴纸形状',
  '引擎',
  '空闲',
  '导入游戏',
  '就绪',
  '可用，但没有管理员权限',
  '此处不可用',
  '已保存的生成',
  '导入会写入正在运行的游戏。之后请保存并重新载入这张贴纸 —— FH6 只有那时才会重建它。',
  '打开库文件夹',
  '大小',
  '角度',
  '大约还剩 {t}',
  '松手即可',
  '椭圆',
  '矩形',
  '三角形',
  '新建图层',
  '把形状移到这里',
  '选中整个图层',
  '锁定',
  '隐藏',
  '名称',
  '日期',
  '选择',
  '全选',
  '取消',
  '今天',
  '昨天',
  '更早',
  '删除 {n} 次生成？',
  '它们会连同形状一起永久消失。',
  '素材库',
  '超出游戏 3000 上限',
  '原图',
  '从零创建',
  '专家调校',
  '引擎自身的默认值，可编辑。出厂已调好；修改可用时间换质量，或追求特定风格。圆点标记已改项。',
  '全部重置',
  '平滑与锐利',
  '边缘与形状',
  '搜索与质量',
  '联合抛光',
  '放置后统一微调所有形状。关闭 = 原始结果：更快，更粗糙。',
  '抛光迭代数',
  '迭代越多，边缘与颜色越稳定。时间随数值增长。',
  '最终边缘柔度',
  '锐化的终点。越低边缘越锐利，越高过渡越柔和。',
  '半透明形状',
  '半透明图层用更少的形状构建平滑渐变。关闭 = 全部不透明。',
  '不透明度下限',
  '形状最多能有多透明。越高越锐利，但渐变需要更多形状。',
  '细节权重',
  '拟合偏向细节区域的程度。0 = 所有像素等权。',
  '最大拉伸',
  '形状可拉长的程度。越高越会用细条描摹轮廓。',
  '形状种类',
  '逗号列表：ellipse、triangle、rectangle。种类越少风格越强。',
  '种类配比',
  '各种类的占比，顺序与上表一致。',
  '贴边缩形',
  '在强边缘附近缩小候选形状。有利于人像；不利于文字和平面图形。',
  '回填重置',
  '把最没用的形状对着成品重新放置。绝不更差，耗时。',
  '偏好紧凑形状',
  '惩罚横跨无关区域的松散形状。',
  '突兀形状清理',
  '移除边缘画出图中不存在棱线的形状。0 = 关闭；请用眼判断。',
  '搜索网格',
  '放置搜索的网格。更细可瞄准小细节，起步分布更散。',
  '搜索预设',
  '统一控制下方搜索预算。单独编辑的数字覆盖档位。',
  '随机种子',
  '相同种子和设置得到相同结果。修改可重新洗牌构图。',
  '每形状候选数',
  '每个形状尝试的随机放置数。越多拟合越好，越慢。',
  '精修次数',
  '用于改进每个形状最佳候选的爬山预算。',
  '评分采样数',
  '给候选评分时采样的像素数。越多越准，越慢。',
  '搜索耐心',
  '连续这么多形状无改进就停止。调高 = 用完全部预算。',
  '超量生成',
  '生成这一倍数的形状并保留最优。仅限不透明风格。',
  '渐变加强',
  '给平滑渐变额外的形状预算，避免可见的碎面。',
  '停止拟合？',
  '目前已放置的形状将被丢弃。',
  '{m} 个形状中只有 {n} 个放得下，其余将在游戏中被丢弃。请使用更大的模板。',
  '拖入一张图片',
  '准备中…',
  '{m} 个形状中的 {n} 个',
  '{n} 个形状 · {b}',
  '重试',
  '键盘快捷键',
  '放弃所做的修改？',
  '你在编辑器中所做的修改将会丢失。',
]);

final _ja = _cat([
  '実行履歴',
  'スタイル',
  '細かさ',
  'ソース',
  '生成',
  '書き出し',
  '注入',
  '編集',
  '切り抜き',
  '前',
  '後',
  'ここに画像をドロップ',
  '写真も絵もロゴも — ビニールの図形になります',
  'ファイルを選択…',
  '別のを選ぶ…',
  '準備完了 — スタイルと細かさを選んで生成',
  '画像なし',
  '図形を構築中',
  '完了',
  '失敗',
  '注入できます',
  '図形の構築',
  'エッジの仕上げ',
  '仕上げ',
  'アクティビティ',
  'すべて',
  '問題',
  '結果',
  'コピー',
  'クリア',
  '閉じる',
  '完了',
  'リセット',
  '切り抜きを適用',
  '自由',
  'テンプレート',
  '詳細設定…',
  '検索',
  '開く',
  '削除',
  'まだ何もありません — 完了した生成はここに残ります。',
  '該当する実行はありません。',
  '取り消す',
  'やり直す',
  '実行履歴に保存',
  '編集中',
  '未選択',
  '色',
  '不透明度',
  'レイヤー',
  '下へ',
  '上へ',
  '左右反転',
  '上下反転',
  '複製',
  'FH6 に注入',
  'テンプレートのレイヤー数',
  'エディタで開いているグループの正確なレイヤー数',
  '拡大率',
  'この後 FH6 でビニールを保存して読み込み直してください',
  '書き込み中…',
  '推定中…',
  'エンジンが起動しませんでした',
  'すべて',
  '使い方',
  '画像を選ぶ',
  _en['helpStep1Body']!,
  'スタイルと大きさを選ぶ',
  _en['helpStep2Body']!,
  '生成する',
  _en['helpStep3Body']!,
  'ゲームを開く',
  _en['helpStep4Body']!,
  '転送する',
  _en['helpStep5Body']!,
  _en['helpWarning']!,
  '停止',
  '表示',
  'キャンセル',
  '読み込む',
  'この実行を読み込みますか？',
  'いまキャンバスにあるものは置き換えられます。',
  'この実行を削除しますか？',
  'この操作は取り消せません。',
  'この設定を保存…',
  'マイプリセット',
  'プリセット名',
  '保存',
  '詳細設定',
  '1回あたりの試行数',
  'パイプライン全体をN回実行して最良の結果を残します。時間もN倍かかります。',
  '診断',
  'ログフォルダーを開く',
  'パスをコピー',
  'うまくいかないときは、このファイルを送ってください。',
  '元の解像度で処理',
  '画像の実際の解像度でフィットします。大きな画像ではかなり遅くなります。',
  '図形を画像の中に収める',
  'すべての図形が画像内に収まり、端からはみ出しません。',
  '高速モード',
  '候補の4分の1だけを評価します。かなり速い代わりに誤差が2〜6%増えます。',
  '輪郭項を外す',
  '約半数の画像では良くなり、残りでは悪くなります。目で比べてください。',
  '偽エッジ項を外す',
  '結果が柔らかすぎると感じたら切ってください。',
  '単色',
  'きれいな切り抜きに単色を一つ。グレーのアンチエイリアス縁は出ません。',
  '省エネモード',
  '構築しながら各図形を再フィットします。1500図形以下が最適です。',
  '個の図形',
  'ステッカー',
  'バンパー',
  '最大',
  '数値を直接入力',
  '設定',
  '完了時に音を鳴らす',
  '図形ができあがったときに短い音が鳴ります。',
  '完了時にタスクバーを点滅',
  'ウィンドウが背面にあるときだけです。',
  'ログ',
  '選択',
  '編集',
  '描画中…',
  '画像がビニールの図形になります',
  'エンジン',
  '待機中',
  'ゲームへ転送',
  '準備完了',
  '利用可能（管理者権限なし）',
  'ここでは利用できません',
  '保存済みの実行',
  '転送は実行中のゲームに書き込みます。そのあとビニールを保存して読み込み直してください — FH6 はそのときだけ作り直します。',
  'ライブラリのフォルダーを開く',
  'サイズ',
  '角度',
  '残り約 {t}',
  'ここで離す',
  '楕円',
  '長方形',
  '三角形',
  '新規レイヤー',
  '図形をここへ移動',
  'レイヤー全体を選択',
  'ロック',
  '非表示',
  '名前',
  '日付',
  '選択',
  'すべて',
  '解除',
  '今日',
  '昨日',
  'それ以前',
  '{n} 件の実行を削除しますか？',
  '図形ごと完全に消えます。',
  'バンク',
  'ゲームの上限3000を超えています',
  '元画像',
  '一から作成',
  'エキスパート調整',
  'エンジン自身の既定値を編集できます。出荷時に調整済み。時間と品質の交換や作風の追求に。点は変更済みの印。',
  'すべてリセット',
  '滑らかさとシャープさ',
  'エッジと図形',
  '探索と品質',
  '一括ポリッシュ',
  '配置後に全図形をまとめて磨きます。オフ = 生の結果：速いが粗い。',
  'ポリッシュ反復回数',
  '回数を増やすほどエッジと色が落ち着きます。時間は数に比例。',
  '最終エッジの柔らかさ',
  'シャープ化の終点。低い = 鋭いエッジ、高い = 柔らかいなじみ。',
  '半透明図形',
  '半透明の層は少ない図形で滑らかなグラデーションを作ります。オフ = 全図形不透明。',
  '不透明度の下限',
  '図形が許される透明度。高い = くっきり、ただしグラデーションは図形数を要します。',
  'ディテール重み',
  '細部をどれだけ優先するか。0 = 全ピクセル同等。',
  '最大伸長',
  '図形をどこまで細長くできるか。高いほど細い帯で輪郭をなぞります。',
  '図形の種類',
  'カンマ区切り：ellipse、triangle、rectangle。種類が少ないほど様式的。',
  '種類の配合',
  '各種類の割合。上のリストと同じ順。',
  'エッジ考慮サイズ',
  '強いエッジ付近で候補を縮小。人物向き；文字やフラット絵には不向き。',
  '再配置パス',
  '役に立たない図形を完成画に対して置き直します。悪化はせず、時間がかかります。',
  'コンパクトな図形を優先',
  '無関係な領域にまたがる図形にペナルティ。',
  '浮き図形の掃除',
  '画像にない稜線を描く図形を除去。0 = オフ；結果は目で判断。',
  '探索グリッド',
  '配置探索のセル。細かいほど小さな細部を狙い、初期配置は散ります。',
  '探索プリセット',
  '下の探索予算をまとめて切り替え。個別に編集した数値が優先。',
  'シード',
  '同じシードと設定なら同じ結果。変えると構図を引き直します。',
  '図形ごとの候補数',
  '図形ごとに試すランダム配置の数。多い = 良い当てはめ、遅い。',
  '磨き込み回数',
  '各図形の最良候補を改善する山登り予算。',
  'スコア標本数',
  '候補の採点に使うピクセル数。多い = 正確、遅い。',
  '探索の我慢',
  '改善なしの図形がこの数続いたら停止。高い = 予算を使い切る。',
  'オーバードロー',
  'この倍数だけ多く生成し、最良だけ残します。不透明スタイル専用。',
  'グラデーション強化',
  '滑らかなグラデーションに追加の図形予算を与え、面割れを防ぎます。',
  '生成を停止しますか？',
  'これまでに配置された図形は破棄されます。',
  '{m} 個中 {n} 個の図形しか収まりません。残りはゲーム内で破棄されます。より大きなテンプレートを使ってください。',
  '画像をドロップ',
  '準備中…',
  '{m} 個中 {n} 個の図形',
  '{n} 個の図形 · {b}',
  '再試行',
  'キーボードショートカット',
  '編集内容を破棄しますか？',
  'エディタで加えた変更は失われます。',
]);

final _ko = _cat([
  '실행 기록',
  '스타일',
  '디테일',
  '원본',
  '생성',
  '내보내기',
  '주입',
  '편집',
  '자르기',
  '이전',
  '이후',
  '여기에 이미지를 놓으세요',
  '사진도 그림도 로고도 — 비닐 도형이 됩니다',
  '파일 선택…',
  '다른 파일…',
  '준비됨 — 스타일과 디테일을 고르고 생성하세요',
  '이미지 없음',
  '도형 만드는 중',
  '완료',
  '실패',
  '주입할 수 있습니다',
  '도형 만들기',
  '가장자리 다듬기',
  '마무리',
  '활동',
  '전체',
  '문제',
  '결과',
  '복사',
  '지우기',
  '닫기',
  '완료',
  '초기화',
  '자르기 적용',
  '자유',
  '템플릿',
  '고급 설정…',
  '검색',
  '열기',
  '삭제',
  '아직 저장된 것이 없습니다 — 완료된 실행이 여기에 쌓입니다.',
  '일치하는 실행이 없습니다.',
  '실행 취소',
  '다시 실행',
  '실행 기록에 저장',
  '편집 중',
  '선택된 것 없음',
  '색상',
  '불투명도',
  '레이어',
  '뒤로',
  '앞으로',
  '좌우 반전',
  '상하 반전',
  '복제',
  'FH6에 주입',
  '템플릿 레이어 수',
  '에디터에서 열려 있는 그룹의 정확한 레이어 수',
  '배율',
  '주입 후 FH6에서 비닐을 저장하고 다시 불러오세요',
  '기록 중…',
  '추정 중…',
  '엔진이 시작되지 않았습니다',
  '전체',
  '사용 방법',
  '이미지 고르기',
  _en['helpStep1Body']!,
  '스타일과 크기 고르기',
  _en['helpStep2Body']!,
  '생성하기',
  _en['helpStep3Body']!,
  '게임 열기',
  _en['helpStep4Body']!,
  '옮기기',
  _en['helpStep5Body']!,
  _en['helpWarning']!,
  '중지',
  '보기',
  '취소',
  '불러오기',
  '이 실행을 불러올까요?',
  '지금 캔버스에 있는 것이 대체됩니다.',
  '이 실행을 삭제할까요?',
  '되돌릴 수 없습니다.',
  '이 설정 저장…',
  '내 프리셋',
  '프리셋 이름',
  '저장',
  '고급 설정',
  '실행당 시도 횟수',
  '전체 파이프라인을 N번 실행하고 가장 좋은 결과를 남깁니다. 시간도 N배 걸립니다.',
  '진단',
  '로그 폴더 열기',
  '경로 복사',
  '문제가 생기면 이 파일을 보내 주세요.',
  '원본 해상도 사용',
  '이미지의 실제 해상도로 맞춥니다. 큰 원본에서는 훨씬 느립니다.',
  '도형을 이미지 안에 유지',
  '모든 도형이 이미지 안에 머물러 가장자리로 넘치지 않습니다.',
  '빠른 모드',
  '후보의 4분의 1만 평가합니다. 훨씬 빠르지만 오차가 2-6% 늘어납니다.',
  '윤곽 항 제거',
  '절반 정도의 이미지에서 좋아지고 나머지는 나빠집니다. 눈으로 비교하세요.',
  '거짓 경계 항 제거',
  '결과가 너무 부드러워 보이면 끄세요.',
  '단색',
  '깔끔한 누끼에 단색 하나. 회색 앤티앨리어싱 가장자리가 없습니다.',
  '절약 모드',
  '만들면서 각 도형을 다시 맞춥니다. 1500개 이하에서 가장 좋습니다.',
  '개 도형',
  '스티커',
  '범퍼',
  '최대',
  '직접 숫자 입력',
  '설정',
  '완료되면 소리 재생',
  '도형이 준비되면 짧은 알림음이 울립니다.',
  '완료 시 작업 표시줄 깜빡임',
  '창이 뒤에 있을 때만.',
  '로그',
  '선택',
  '편집',
  '그리는 중…',
  '그림이 비닐 도형이 됩니다',
  '엔진',
  '대기 중',
  '게임으로 전송',
  '준비됨',
  '사용 가능, 관리자 권한 없음',
  '여기서는 사용할 수 없음',
  '저장된 실행',
  '전송은 실행 중인 게임에 직접 씁니다. 그 뒤 비닐을 저장하고 다시 불러오세요 — FH6는 그때만 다시 만듭니다.',
  '라이브러리 폴더 열기',
  '크기',
  '각도',
  '약 {t} 남음',
  '여기에 놓으세요',
  '타원',
  '사각형',
  '삼각형',
  '새 레이어',
  '도형을 여기로 이동',
  '레이어 전체 선택',
  '잠금',
  '숨기기',
  '이름',
  '날짜',
  '선택',
  '전체',
  '해제',
  '오늘',
  '어제',
  '이전',
  '실행 {n}개를 삭제할까요?',
  '도형과 함께 완전히 사라집니다.',
  '뱅크',
  '게임 한도 3000 초과',
  '원본',
  '처음부터 만들기',
  '전문가 튜닝',
  '엔진 자체 기본값을 직접 편집합니다. 이미 조율되어 있으며, 시간과 품질을 맞바꾸거나 원하는 스타일을 찾을 때 바꾸세요. 점은 변경된 항목 표시입니다.',
  '모두 재설정',
  '부드러움과 선명함',
  '가장자리와 도형',
  '탐색과 품질',
  '공동 폴리싱',
  '배치 후 모든 도형을 함께 다듬습니다. 끄면 = 원시 결과: 더 빠르고 더 거칠어요.',
  '폴리싱 반복 수',
  '반복이 많을수록 가장자리와 색이 더 안정됩니다. 시간은 수에 비례해요.',
  '최종 가장자리 부드러움',
  '샤프닝이 끝나는 지점. 낮게 = 더 선명한 가장자리, 높게 = 더 부드러운 혼합.',
  '반투명 도형',
  '반투명 층은 더 적은 도형으로 매끄러운 그라데이션을 만듭니다. 끄면 = 전부 불투명.',
  '불투명도 하한',
  '도형이 가질 수 있는 최대 투명도. 높게 = 더 선명하지만 그라데이션에 도형이 더 필요해요.',
  '디테일 가중치',
  '세밀한 영역을 얼마나 우선하는지. 0 = 모든 픽셀 동일.',
  '최대 늘이기',
  '도형이 얼마나 길어질 수 있는지. 높으면 가는 띠로 윤곽을 따라갑니다.',
  '도형 종류',
  '쉼표 목록: ellipse, triangle, rectangle. 종류가 적을수록 더 양식화된 느낌.',
  '종류 비율',
  '각 종류의 비중, 위 목록과 같은 순서.',
  '가장자리 인식 크기',
  '강한 가장자리 근처에서 후보를 줄입니다. 인물에 유리; 문자·플랫 그림엔 불리.',
  '재배치 패스',
  '가장 쓸모없는 도형을 완성본에 맞춰 다시 놓습니다. 나빠지진 않고, 시간이 듭니다.',
  '조밀한 도형 선호',
  '무관한 영역을 가로지르는 도형에 벌점을 줍니다.',
  '튀는 도형 정리',
  '그림에 없는 모서리를 그리는 도형을 제거. 0 = 끔; 결과는 눈으로 판단하세요.',
  '탐색 격자',
  '배치 탐색의 칸. 촘촘할수록 작은 디테일을 노리고, 시작 분포는 흩어집니다.',
  '탐색 프리셋',
  '아래 탐색 예산을 한 번에 정합니다. 직접 고친 숫자는 단계를 덮어씁니다.',
  '시드',
  '같은 시드와 설정이면 같은 결과. 바꾸면 구도를 다시 섞습니다.',
  '도형당 후보 수',
  '도형마다 시도하는 무작위 배치 수. 많을수록 = 더 좋은 맞춤, 더 느림.',
  '다듬기 횟수',
  '각 도형의 최고 후보를 개선하는 언덕오르기 예산.',
  '점수 표본 수',
  '후보 점수에 쓰는 픽셀 표본 수. 많을수록 = 정확, 느림.',
  '탐색 인내심',
  '연속 이만큼의 도형이 개선 없으면 중단. 높게 = 예산 전부 사용.',
  '초과 생성',
  '이 배수만큼 더 생성하고 최고만 남깁니다. 불투명 스타일 전용.',
  '그라데이션 보강',
  '매끄러운 그라데이션에 도형 예산을 더 주어 면 갈라짐을 막습니다.',
  '생성을 중지할까요?',
  '지금까지 배치된 도형은 삭제됩니다.',
  '{m}개 중 {n}개 도형만 들어갑니다. 나머지는 게임에서 버려집니다. 더 큰 템플릿을 사용하세요.',
  '이미지를 끌어다 놓으세요',
  '준비 중…',
  '도형 {m}개 중 {n}개',
  '도형 {n}개 · {b}',
  '다시 시도',
  '키보드 단축키',
  '편집 내용을 버릴까요?',
  '편집기에서 변경한 내용이 사라집니다.',
]);

/// The same order the previous studio offered, so a returning user finds their
/// language where they left it.
final languages = <Lang>[
  Lang('en', 'English', _en),
  Lang('uk', 'Українська', _uk),
  Lang('de', 'Deutsch', _de),
  Lang('es', 'Español', _es),
  Lang('pt-BR', 'Português (BR)', _ptBR),
  Lang('fr', 'Français', _fr),
  Lang('pl', 'Polski', _pl),
  Lang('it', 'Italiano', _it),
  Lang('tr', 'Türkçe', _tr),
  Lang('zh-CN', '中文(简体)', _zhCN),
  Lang('ja', '日本語', _ja),
  Lang('ko', '한국어', _ko),
];

Lang langFor(String code) =>
    languages.firstWhere((l) => l.code == code, orElse: () => languages.first);

/// Picks a language from the OS locale on first run: an exact code first, then
/// the bare language, so `pt-PT` lands on Brazilian Portuguese rather than
/// English and `de-AT` on German.
Lang langForSystem(String systemLocale) {
  final tag = systemLocale.replaceAll('_', '-');
  for (final l in languages) {
    if (l.code.toLowerCase() == tag.toLowerCase()) return l;
  }
  final base = tag.split('-').first.toLowerCase();
  for (final l in languages) {
    if (l.code.split('-').first.toLowerCase() == base) return l;
  }
  return languages.first;
}

/// Makes the current language reachable from any widget without threading it
/// through every constructor, and rebuilds everything below when it changes.
class Strings extends InheritedWidget {
  const Strings({super.key, required this.lang, required super.child});

  final Lang lang;

  static Lang of(BuildContext context) {
    final s = context.dependOnInheritedWidgetOfExactType<Strings>();
    return s?.lang ?? languages.first;
  }

  @override
  bool updateShouldNotify(Strings old) => old.lang.code != lang.code;
}

/// `context.s('generate')` — short because it appears in every label.
extension StringsX on BuildContext {
  String s(String key) => Strings.of(this).get(key);
}
